# Suy nghĩ về thế kỷ mới của người tu Phật {- #the-ky-moi-cua-nguoi-tu-phat}

<div class="align-right">
*Giảng tại Thường Chiếu, 1998*
</div>

Nhân loại sắp bước vào thiên niên kỷ mới với một nền văn minh ngày càng rực rỡ. Khoa học hiện đại được xem gần như là vạn năng, phục vụ mọi nhu cầu vật chất trong đời sống của con người. Thế nhưng, con người đã thật sự hạnh phúc, thật sự chấm dứt khổ đau hay chưa? Đó là điều chúng ta cần phải suy ngẫm.                                                               

Đức Phật sau bốn mươi chín ngày đêm thiền định dưới cội Bồ-đề, khi sao mai vừa mọc Ngài liền thành đạo và tuyên bố: Như Lai là người đã diệt tận cội gốc vô minh, chấm dứt mọi khổ đau, thật sự an vui giải thoát. Bài pháp đầu tiên tại vườn Lộc Uyển là bài Tứ Diệu Đế, đức Phật nói về bốn chân lý chắc thật của cuộc đời là Khổ, Tập, Diệt, Đạo. Trong đó, khổ là một lẽ thực của cuộc đời. Mới nghe qua, chúng ta thấy dường như đạo Phật thật là bi quan. Nhưng đi sâu vào, thấm nhuần giáo lý của đức Phật rồi, chúng ta thấy ngược lại. Bởi Phật nói khổ *(khổ đế)* là ở trên quả mà nói, vì quả là cái người ta dễ thấy dễ biết. Khi biết được quả rồi, thì Ngài liền chỉ đến nhân. Nguyên nhân nào tạo ra quả khổ ấy *(tập đế)*. Khi biết rõ nguyên nhân rồi, chúng ta liền dẹp hết nhân *(đạo đế)* thì khổ nhất định sẽ không còn, chừng ấy quả an vui giải thoát sẽ hiện tiền *(diệt đế)*. Vậy vui là mục đích đức Phật nhắm đến, khổ là chỗ đức Phật chỉ ra để chúng ta tìm lại nguyên nhân và dẹp sạch nó đi thì quả vui sẽ đến với chúng ta.

Các nhà khoa học cũng thế, luôn luôn phăng tìm manh mối của vạn tượng sum la này; căn cứ trên quả mà phăng tới nhân, không bao giờ đi từ nhân tới quả. Vì quả dễ thấy, dễ nói hơn nhân. Ví dụ bây giờ chúng ta có quả cam ngon, người thưởng thức được quả cam sẽ hỏi: Quả cam này từ đâu mà có? Tự nhiên chúng ta sẽ giải thích: Từ hạt cam ương lên, nẩy mầm, ra cây, có lá, có hoa rồi kết thành trái. Vậy quả là cái hiện thấy, chứng minh được. Còn nhân thì đã cũ đã xưa rồi, chúng ta khó có thể chỉ cho người khác thấy tường tận được. Đó là việc cụ thể. Cho nên tinh thần Phật dạy rất thích hợp với khoa học hiện giờ, hay ngược lại khoa học hiện giờ rất thích hợp với tinh thần của đạo Phật. Vì thế, đạo Phật rất thực tế, luôn trung thực với cuộc đời chớ không phải bi quan yếm thế như nhiều người vẫn nghĩ.

Có thể nói, trở lại phăng tìm cội gốc của mọi sự khổ để diệt trừ nó, sống lại với con người chân thật của chính mình là một việc làm khoa học trên khoa học. Tại sao chúng tôi dám nói như vậy? Là vì khoa học tìm kiếm phát minh về vật chất để phục vụ cho con người vật chất. Mà con người vật chất lại là một con người tạm bợ, vô thường, sáng còn tối mất.

Khoa học có thể cống hiến cho nhân loại những thành tựu mới lạ tinh vi nhằm thỏa mãn cuộc sống tiện nghi cho họ, nhưng không thể ngăn chặn được lòng tham lam, sân hận, si mê nơi con người. Mà hễ còn tham lam, sân hận, si mê là còn khổ đau. Bởi vì với một con người đầy dẫy tham sân si, thì càng phát minh chỉ càng đưa đến tranh đấu, giành giựt và cuối cùng đi đến đánh nhau rồi chết chóc, thù hận mà thôi.

Thí dụ chỉ cần một trái bom nguyên tử trong bàn tay của kẻ hiếu chiến thì không quá một phút, có cả hàng vạn người tan nát ra tro, chưa kể đến những tổn thất vật chất khác nữa, thật là tội lỗi! Như vậy khoa học chỉ càng gieo rắc khổ đau thêm cho nhân loại, chớ không thể đem đến an vui hạnh phúc được. Nói như vậy không có nghĩa chúng tôi phủ nhận những thành tựu lớn lao của khoa học. Nhưng nếu được vừa tìm lại mình, vừa biết hết bên ngoài thì hay biết mấy! Đức Phật dạy chúng ta xoay lại chính mình trước, đoạn tận mọi thứ phiền não si mê rồi thì tự nhiên sẽ chinh phục được vũ trụ bên ngoài sau, là vì vậy.

Chúng ta dù biết hết cả vũ trụ ở ngoài mà không biết mình thì đã thực tế đâu? Phát minh được những việc bên ngoài, giúp đỡ cho cái thân tạm bợ mà cho là quan trọng, trong khi phát minh cái chân thật bất sanh bất diệt của mình để nhận và sống được với nó thì chúng ta lại xem thường, lại lơ là! Tại sao các nhà bác học giam mình trong phòng kín nghiền ngẫm về một vấn đề nào đó thì cho là tích cực; trong khi ngồi lại, thiền định yên lặng để tìm ra con người chân thật nơi mình thì lại xem là tiêu cực? Như vậy cái nhìn của chúng ta có đúng không?

Đạo Phật là đạo của trí tuệ và từ bi, đạo của giác ngộ giải thoát. Tất cả pháp môn của Phật dạy đều phải trở về chỗ chân thật của mình bằng chính định lực và trí tuệ của mình. Trở về được chỗ chân thật là an vui hạnh phúc, chấm dứt mầm mống của mọi sự khổ đau. Lúc đó, chúng ta mới có thể thông cảm, tha thứ, thương yêu và giúp đỡ đồng loại như chính bản thân mình. Cho nên chúng ta cứ cầu giải thoát, mà không biết giải thoát ra sao, muốn được hạnh phúc mà không biết thế nào là hạnh phúc? Thật ra hạnh phúc chân thật trong đạo Phật chính là giác ngộ giải thoát. Mà giải thoát là biết cái hư giả của thân và tâm này, nên không còn lệ thuộc vào nó, không chạy theo nó, không còn tạo nghiệp nữa. Không còn tạo nghiệp tức là không còn khổ đau. Không còn khổ đau tức là hạnh phúc.

Với người biết tu thì cuộc sống vật chất của thân tứ đại này không có gì quan trọng cả. Phải làm chủ được mình, giúp mọi người cùng vượt lên trên những thứ phiền não trói buộc, sống an vui giữa những thay đổi của cuộc đời, chết thảnh thơi nhẹ nhàng như thay một chiếc áo mới, là mục đích chính của người tu Phật. Chúng ta nhìn lại xem những vị tu hành thâm nhập đạo lý sâu, sống được với đạo, không bao giờ lắc đầu chặc lưỡi thở dài, mà thường cười hoài. Bao nhiêu đó cũng đủ cho thấy đạo Phật đến với cuộc đời như thế nào rồi. Đặc biệt là đạo Phật ở nước ta.

Trong thời Lý-Trần, đạo Phật được xem như Quốc giáo. Với một nền giáo lý nhập thế cơ bản, Phật giáo Việt Nam luôn có mặt, luôn gắn bó với vận mệnh của đất nước. Lúc thăng lúc trầm, khi ẩn khi hiện, nhưng chưa bao giờ vắng thiếu trên đất nước ta. Đó chính là chân tinh thần đạo pháp không lìa thế gian, không lìa cuộc đời mà có vậy. Nếu không thế thì đạo Phật không thể tồn tại trong lòng dân tộc, trong lòng nhân loại được.

Cho nên khoa học càng tiến thì nền tảng đạo đức của con người lẽ ra phải càng cao, giá trị tâm linh phải càng sáng mới có thể dừng bớt những nguy cơ cho nhân loại. Nếu chúng ta chưa thấy rõ tầm quan trọng đó thì nền khoa học hiện đại bước vào thế kỷ mới sẽ không thể cứu vãn nhân loại thoát khỏi mọi thứ hiểm họa được. Thiên tai, bệnh tật, chiến tranh, ghiện ngập v.v…. đều xuất phát từ một nền tảng đạo đức suy đồi, từ lòng tham lam và si mê vô bờ của con người.

Chúng tôi thiết nghĩ, không thể có được nguồn an vui hạnh phúc chân thật khi con người chưa nhận ra và diệt trừ được nguồn gốc của khổ đau. Không thể có được một nền văn minh sáng rực khi giá trị tâm linh của con người đã bị lu mờ. Muốn thế, nhân loại phải biết trở lại với cái chân thật luôn hằng hữu bên mình. Bởi vì phát minh và làm chủ được chính mình cũng có nghĩa là phát minh và làm chủ được toàn thể vũ trụ này.

Muốn thế, chúng ta hãy thử một lần đến và chiêm nghiệm giáo lý của đức Phật bằng chính sự thực hành của mình xem sao!
