# Người tu Phật là người tìm về nguồn an lạc giải thoát {- #tim-ve-giai-thoat}

<div class="align-right">
*Giảng tại chùa Xá Lợi, 1998*
</div>

Đề tài chúng tôi nhắc nhở quý vị hôm nay là: *“Người tu Phật là tìm trở về nguồn an lạc giải thoát”*. Quý vị chú ý nghe, lãnh hội đầy đủ và ứng dụng tu hành thì mới tốt.

Đức Phật sau khi thành đạo dưới cội Bồ đề, Ngài tìm những người bạn đồng tu lúc trước là năm anh em ông Kiều Trần Như để thuyết pháp. Bài pháp đầu tiên là Tứ diệu đế, trong đó đế thứ nhất là Khổ đế, nói cái khổ là lẽ thực của cuộc đời này. Đức Phật nói khổ, tại sao chúng tôi lại nói người tu là tìm về nguồn an lạc giải thoát, tức là vui. Như vậy có trái với bản ý của đức Phật hay không?

Khi mới nhìn qua đạo Phật, người không hiểu thấy đạo Phật dường như bi quan, yếm thế. Nhưng đi sâu, thấm nhuần giáo lý của Phật rồi, chúng ta mới thấy ngược lại. Đức Phật nói khổ là chỉ trên quả, vì quả dễ thấy, dễ biết. Khi biết được quả rồi, Ngài liền chỉ đến nhân. Nguyên nhân nào tạo ra quả khổ ấy. Khi biết được nhân rồi, dẹp hết nhân thì quả không còn.

Ngày nay các nhà khoa học luôn phăng tìm manh mối của vạn tượng sum la, căn cứ trên quả mà phăng tới nhân, không bao giờ đi từ nhân tới cái quả. Vì quả là cái dễ thấy, thấy quả rồi chúng ta tìm ra nhân dễ dàng, còn trước nói nhân sau đó mới chỉ quả thì khó hơn. Như bây giờ chúng ta có cây cam, được quả cam ăn, biết quả cam ngọt. Những người thưởng thức mùi vị quả cam hỏi rằng: Cam này từ đâu có? Tự nhiên chúng ta sẽ giải thích từ hạt cam ươm lên, nẩy mầm, lên cây, có lá, đơm hoa, kết quả. Quả là cái hiện thấy, chứng minh được; còn nhân thì đã cũ, đã xưa rồi, chúng ta không thể nào chỉ cho người khác thấy tường tận. Cho nên tinh thần Phật dạy rất thích hợp với khoa học hiện giờ.

Nếu người không hiểu, nghe đức Phật nói cuộc đời là khổ, mang thân này là khổ thì cho rằng đạo Phật bi quan, đạo Phật chán đời, v.v… Khổ đó là quả, chúng ta biết rồi thì phải phăng tìm nguyên nhân của nó. Nếu biết được nhân nào tạo ra quả khổ, chúng ta liền dẹp bỏ, tự nhiên quả khổ không còn. Nếu quả khổ không còn, lúc đó được vui. Vui không riêng có mà chỉ khi nào hết khổ. Đó là tinh thần của Phật dạy.

Phật nói khổ để chúng ta tìm ra nguyên nhân gây đau khổ, biết rõ nguyên nhân rồi thì dứt bỏ nó. Dứt bỏ rồi chúng ta mới hết khổ, tức là được an lạc, giải thoát. Vậy mục đích của đức Phật dạy là muốn chúng ta hết khổ, được giải thoát, chớ không phải dạy chúng ta chịu khổ. Phương pháp tu đó không hề bi quan. Quý vị nhìn những người tu hành hiểu sâu đạo lý, sống được với đạo, thường lắc đầu, chặc lưỡi, thở dài hay thường cười hoài? Bao nhiêu đó cũng tự trả lời cho những vấn đề chúng ta cần hiểu rồi.

Người biết tu luôn phăng tận nguồn gốc nguyên nhân gây ra đau khổ, dẹp bỏ chúng qua một bên thì đau khổ không còn. Khổ hết gọi là an vui. Nhưng thật đáng thương cho Phật tử chúng ta ngày nay, tu mà không tìm nguyên nhân của khổ để dẹp bỏ, lại cứ cầu Phật cho con hết khổ hoài. Gặp việc buồn, việc khổ liền vô chùa thắp hương, lạy Phật tha thiết, xin Phật ban cho con ân huệ để con hết khổ. Việc gì cũng dựa vào quyền lực của đức Phật chớ không bỏ ra công phu tu hành.

Đạo Phật là đạo rất thực tế chớ không phải huyền bí, nhưng Phật tử chúng ta quen bệnh yếu đuối nên xem Phật giống như ông thần. Gặp việc gì khổ quá chỉ xin với Phật cho bớt khổ, chớ không biết tu cho bớt khổ. Đó là điểm yếu đuối, sai lầm của Phật tử chúng ta. Người tu Phật thì phải tìm về nguồn an lạc giải thoát. Tôi xin nêu vài điểm căn bản cho quý vị thấy nguồn gốc của an lạc giải thoát.

Trong kinh Phật thường nói: *“Chúng sinh có tám điều khổ: sanh khổ, già khổ, bệnh khổ, tử khổ, ái biệt ly khổ, cầu bất đắc khổ, oán tắng hội khổ và ngũ ấm xí thạnh khổ. Đó là bát khổ”*. Như vậy khổ nhiều hơn vui. Chúng ta xét kỹ xem, cái khổ đó là khổ cho tất cả mọi người hay chỉ đối với những ai không biết đạo lý?

**1. Sanh khổ **

Theo nhà Phật thì sanh gồm hai phần. Thứ nhất, sau khi ra khỏi lòng mẹ đau đớn nhọc nhằn. Thứ hai, trong cuộc sống của chúng ta, nếu không biết tu, không hiểu đạo thì cả cuộc đời chỉ toàn là đau khổ, không chút an vui. Như vậy khổ lúc sanh ra và khổ trong cuộc sống. Khi sanh ra có đứa bé nào cười không, hay đều khóc oa oa. Đó là vì ra đời khó khăn đau đớn quá, nên lọt lòng mẹ là khóc liền. Cái khóc ấy nói lên sinh là khổ.

Rồi từ bé đến già mấy mươi năm, một cuộc đời khổ nhiều vui ít. Quý vị thử kiểm lại xem trong suốt một đời, những gì chúng ta mong muốn, đa phần được như ý hay chỉ thiểu phần như ý? Chắc rằng không ai nói đa phần như ý. Người thì gia đình ấm no có cơm ăn, áo mặc nhưng con cháu khó dạy. Người thì con cháu dễ dạy nhưng gia đình lại chật vật thiếu thốn v.v… đủ thứ thuận nghịch, không khi nào được thỏa mãn như ý của mình. Vì vậy đa số đều bất như ý.

Con người sinh ra ai cũng mơ ước tràn đầy hạnh phúc, nhưng trải qua bốn, năm mươi tuổi nhìn lại cuộc đời không có hạnh phúc mà bất hạnh lại nhiều. Ít hôm nghe tin người thân mất hoặc phải đi xứ này xứ khác v.v… Hoặc có chuyện này chuyện nọ làm mình phải buồn, phải khổ. Không ai được hạnh phúc trọn vẹn. Cả một đời người, ba phần tư là đau khổ, chỉ một phần tư an vui thôi, thực tế là như vậy.

Chúng ta đã biết sanh là khổ, bây giờ chúng ta phải làm sao cho hết khổ? Làm sao chúng ta sống trong cõi khổ mà vẫn luôn được an vui? Điều đó không có gì khó hết. Nếu sống trong cuộc đời này mà biết rõ ràng cuộc đời là tạm bợ, có rồi sẽ mất, không ai còn mãi. Như vậy ngày nào chúng ta còn sống thì ngày ấy còn tốt, còn có thì giờ cho chúng ta tự tu, cho chúng ta làm những điều thiện, giúp ích mọi người. Một ngày sống là một ngày vàng, chúng ta phải sử dụng hết để lo cho mình, cho người, làm sao cho mình và người đều được an ổn. Làm một điều lành là chúng ta được một nguồn vui. Chúng ta chuyển cuộc sống khổ đau này bằng một cuộc sống tràn đầy hạnh phúc.

Nói như vậy sẽ có vị nghĩ, nếu người giàu có thì giúp đỡ người này, người kia dễ. Còn như ta nghèo, không có điều kiện giúp được ai, thì làm sao có niềm vui. Tôi xin nhắc rằng trên đời có nhiều niềm vui lắm, chỉ sợ chúng ta không chịu làm thôi.

Thí dụ chúng ta không có tiền cho người ăn xin hay đóng góp cứu trợ nạn lụt v.v…, nhưng đang đi thấy đứa bé bị té, chúng ta đỡ lên, vỗ về, an ủi khuyên bảo nó, như vậy có vui không? Chúng ta không làm được việc cứu giúp bằng tiền thì chúng ta làm việc cứu giúp bằng thân, bằng lời. Dùng thân và lời giúp đỡ người bớt khổ. Bớt khổ là họ được vui, người vui thì chúng ta cũng vui. Cái vui đó không tốn gì hết, chỉ tốn một chút công. Như vậy tìm nguồn vui đâu phải khó. Chỉ cần khi thấy một con kiến rớt dưới vũng nước, chúng ta vớt nó lên để trên khô, thấy nó bò mừng rỡ là chúng ta cũng vui rồi.

Người biết tu nhìn lại bản thân mình ngày xưa nhiều nóng giận, nay đã giảm bớt liền cảm thấy vui. Gặp ai đang có nguy khốn, mình ra tay cứu vớt, từ con người cho tới loài vật, giúp được loài nào cũng có nguồn vui. Vậy chúng ta sống để làm lợi ích cho chúng sinh. Tuy rằng khả năng nhỏ bé, hạn hẹp, nhưng với lòng chân thành thì cũng có vui rồi.

Nếu chúng ta biết sống, thì dù đời là khổ hay sanh là khổ, nhưng ngày nào chúng ta cũng lượm cũng mót được nhiều niềm vui. Đó là chúng ta khéo tu, khéo hiểu Phật Pháp, chớ đừng lạy xin Phật cho con vui. Phật không cho được đâu, chúng ta phải tự tạo lấy nguồn vui từ bản thân mình. Tuy sanh khổ, nhưng nếu chúng ta biết sống thì sanh trở thành vui, chớ không phải khổ.

**2. Già khổ**

Tại sao già khổ? Vì già không biết làm gì cứ đi tới đi lui, nhớ con, nhớ cháu, buồn ủ rũ, hết trách người này tới trách người kia, thành ra thấy tuổi già lê thê, đen tối. Nên già là khổ.

Người già nên biết dùng tuổi già trong công việc. Những vị không có trách nhiệm cứ ở tại nhà, tìm những gì hay, những gì đẹp dạy con, dạy cháu. Đem bài kinh hay, đoạn sách tốt để dạy con cháu, đó là vui rồi, đâu phải làm việc gì nhiều. Cũng như chúng tôi, một ngày sống là một ngày phải làm được cái gì cho mình cho người. Lợi ích được cho mình cho người thì vui chớ đâu có khổ. Như vậy nói già khổ hay vui? Già thế nào cũng có kinh nghiệm nhiều hơn người trẻ. Tại sao chúng ta không đem những kinh nghiệm ấy dạy lại cho người sau. Vì vậy tuổi già không phải là thừa, không phải là bỏ. Mỗi ngày chúng ta sống đều có giá trị thì cuộc đời già là vui, chớ không phải khổ.

**3. Bệnh khổ**

Điều này đa số chấp nhận. Có người nào đau mà không rên đâu? Rên tức là khổ chớ gì! Nhiều người than sao tôi bệnh hoạn lê thê, kéo dài năm này qua năm nọ, chán quá! Nên vị đó thấy bệnh là khổ.

Nhưng với con mắt nhà Phật, bệnh cũng không khổ. Vì sao không khổ? Vì Phật dạy thân này do nhân duyên hợp, trong đó có đất, nước, gió, lửa. Kinh Niết Bàn nói tứ đại là bốn con rắn, con rắn nước, con rắn lửa, con rắn đất, con rắn gió. Tôi xin nói cụ thể hơn, con rắn nước là rắn hổ ở dưới nước, con rắn lửa là rắn hổ lửa, con rắn đất là rắn hổ đất, con rắn gió là rắn hổ mây. Bốn con rắn hổ này nhốt trong một cái giỏ thì chúng phải cắn nhau, chống chọi nhau thôi. Người nuôi rắn thấy bốn con cứ chống nhau, làm cho con này con nọ cứ bất an hoài, thì phải can thiệp cho chúng hòa với nhau mới yên được.

Chúng ta mang thân đất nước gió lửa, bốn chất đó có hòa hợp với nhau không? Ít hôm thì lửa thắng nước, lúc đó nóng quá phải kiếm cái gì uống cho mát, đó là điều hòa rắn hổ lửa. Ít hôm nước thắng lửa thì bị lạnh run rẩy, phải kiếm cái gì uống cho ấm, đó là điều hòa con rắn nước. Ít hôm rắn đất bị hổ mây cắn, lúc đó chúng ta kêu trúng gió, phải đánh gió hay tìm cách này cách kia làm cho gió ra thì thân mới nhẹ, nên nói: “Gió thổi mạnh thì đất rung rinh”. Chúng luôn luôn chống chọi nhau. Chúng ta phải điều hòa chúng. Như vậy nhàn hạ hay khổ.

Ai cũng có bệnh. Nếu không bệnh nặng thì cũng bệnh nhẹ, không bệnh nhiều cũng bệnh ít, chớ không ai hoàn toàn không bệnh. Vì bệnh là khổ chung của tất cả mọi loài! Nhiều vị bệnh lăn lộn rên. Rên là khổ. Nhưng giờ đây biết tu, khi bệnh chúng ta phải làm sao? Chúng ta nhìn bốn con rắn này, xem đứa nào thắng, đứa nào bại. Biết rõ bốn con rắn độc đang chống chọi với nhau, chúng ta không chấp thân này là thật. Tứ đại tụ họp nên có thân, nhưng vì tụ họp trong sự chống chọi nên thân này khổ.

Chúng ta biết rõ nó không chắc, không bền, không có gì quan trọng nên bớt khổ. Thường bệnh đau, chúng ta thấy khổ vì thấy thân là hơn hết, vì sợ chết. Nếu biết rõ nó là tướng duyên hợp thì hợp cũng tốt, mà tan cũng vui. Nếu nó còn thì chúng ta dùng vào việc hữu ích, nó mất thì chúng ta ra đi một cách thảnh thơi, có gì đâu mà sợ. Nếu không sợ chết thì đau mặc đau, nó đâu có thiệt.

Ngày xưa có một vị Thiền sư bị bệnh, thầy Tri sự lên thưa: *“Bạch Hòa thượng, Hòa thượng bệnh có cái không bệnh chăng?”*. Ngài đáp: *“Ôi da, ôi da!”*. Cái biết rên đó nó không có hình tướng nên không bị bệnh, còn bệnh là thân này bệnh. Như vậy chúng ta biết ngay nơi thân này là duyên hợp tạm bợ. Có hợp thì phải có tan, không có gì quan trọng. Không quan trọng thì bớt khổ.

Đồng thời chúng ta cũng biết ngay trong thân này có cái chân thật, không hình tướng, nó chính là chủ trì của thân. Biết rõ cái đó thì thân có đau, có nhức là chuyện của thân, nhìn được cái đau tức là chúng ta không đau.

**4. Chết khổ**

Ai cũng thấy người sắp chết thở hổn hển, trăn trở bứt rứt hết sức khổ nhọc, nên nói chết là khổ.

Người nếu khéo tu, nhất là tu thiền sẽ thấy khác. Khi ngồi thiền từ một giờ, lần lần tới một giờ rưỡi, hai giờ, càng tiến lên chân đau vô kể. Nhưng ráng chịu đựng, thắng được nó rồi thì sẽ qua luôn, không còn đau nữa. Thắng được là có gan dạ. Vì có gan dạ nên mới thắng được.

Khi chúng ta chết, thân tứ đại rã rời tan nát, làm sao không đau đớn. Trong khi đau đớn chúng ta nhìn nó biết nó là bại hoại. Còn cái *“biết”* bại hoại đó không bại hoại, không đau đớn. Biết rõ như vậy thì chết không phải khổ nữa. Cho nên ngày xưa Thiền sư Từ Minh ở Trung Hoa có nói câu kệ: *Sanh như đắp chăn đông, tử như cởi áo hạ*. Mùa đông lạnh lẽo được đắp chăn ấm là vui. Mùa hè nóng bức, mồ hôi tươm ướt áo, được cởi áo đi chơi là khỏe. Với người biết tu thì sanh tử như trò chơi, không có gì quan trọng nên không có gì khổ hết.

Chỉ người không biết tu, sống lo bảo vệ, săn sóc, cung dưỡng thân này, nên khi thân này bại hoại, chới với không biết nương tựa vào đâu. Vì vậy mà khổ. Khổ hay vui là tại người biết tu hay không biết tu mà thôi. Thân này tuy có hợp có tan nhưng ông chủ không mất thì còn gì khổ. Vì vậy chết cũng không phải là khổ.

**5. Ái biệt ly khổ**

Tức là người mình thương yêu mà phải xa lìa nên khổ. Nếu chúng ta biết thương yêu là gốc của đau khổ nên bớt thương yêu đi thì bớt khổ.

Nói hết thương yêu, người ta lầm tưởng đạo Phật khô khan quá, không biết thương ai hết. Tôi thường thí dụ, như một dòng suối nhỏ, nước từ đầu nguồn tuôn chảy rất mạnh, vì dòng suối nhỏ mà nước nhiều nên nó chảy xiết. Còn biển cả mênh mông, thấy như không chảy mà thật ra nó chảy ngầm. Nếu không thì làm sao có nước ròng, nước lớn.

Cũng vậy, thế gian cột trói mình trong tình thân thuộc, tình bè bạn, nên khi xa cách phải đau khổ. Còn người tu thì mở rộng lòng thương hết chúng sanh, nên ai chúng ta cũng thương. Vì thương tất cả nên như biển, không chảy xiết nên không khổ. Tình thương có cột trói là khổ, còn lòng từ thương hết mọi người thì không khổ. Người này đi vắng thì còn bao nhiêu người khác chúng ta phải lo cho, có rảnh đâu nhớ thương một người. Như vậy tâm từ bi là tâm tràn trề lai láng, không có hạn cuộc. Còn ái kiến là cột trói, mà cột trói riêng biệt thì khổ. Vì vậy nên nói ái biệt ly khổ. Nếu chúng ta dứt được lòng ái thì tự nhiên khổ theo đó dứt hết, sẽ được vui ngay.

**6. Cầu bất đắc khổ**

Cầu là mong cầu, bất đắc là không được như ý nên khổ. Chúng ta mong muốn hoặc trông chờ điều gì mà không được thì khổ. Nếu chúng ta không thèm mong cầu chi hết, ngày nay sống lo việc ngày nay, không trông đợi ngày mai thì tâm bình an. Ngày nào chúng ta cũng làm tất cả việc tốt, việc lành, cứu người này giúp người kia; không giúp được người thì giúp vật, không cần cầu việc gì cao xa mà chúng ta vẫn được an lành. Do đó chỉ cần dẹp lòng tham cầu thì tự nhiên hết khổ, nên nói hết tâm tham cầu liền được an vui.

**7. Oán tắng hội khổ**

Thù oán mà gặp lại nhau thì khổ. Quý vị ghét ai đó cay đắng mà họ cứ ngồi trước mặt mình hoài, có khổ không? Chắc khổ lắm. Bây giờ chúng ta đừng thèm ghét ai hết thì không còn khổ. Không khổ tức là vui rồi. Như vậy vui từ đâu lại, khổ từ đâu ra? Tại mê muội mà khổ, bỏ mê muội đi thì vui.

Chúng ta thật là đáng thương. Tôi thường nói, như có số người đang đi trên một chiếc thuyền qua biển, sóng gió chòng chành làm thuyền muốn lật. Lúc ấy mọi người có rảnh rỗi để cãi vã, giận hờn nhau không, hay ai cũng lo làm sao cho khỏi chết? Cũng vậy, trên thế gian này ai ai cũng có bao nhiêu thứ hoạn nạn đang chực chờ, nên ai cũng là người đáng thương. Mình đã đáng thương rồi, mọi người xung quanh lại càng đáng thương hơn. Vì vậy thương nhau không hết, có đâu giận hờn làm khổ cho nhau. Ai ưa giận hờn, người đó khôn hay dại?

Vậy mà thế gian không chịu khôn cứ giận hoài, có người còn nói: *“Tôi giận người đó mấy chục năm rồi chưa hết!”*. Vị ấy đâu biết ôm ấp giận trong lòng là mình đang chứa những hòn lửa than, nó sẽ thiêu đốt ta gầy mòn héo hon, vậy mà còn khoe tôi giận mấy chục năm. Giận nhiều thì hại nhiều, không có lợi ích gì cả. Việc qua rồi chúng ta nên xí xóa với nhau rồi cười vui, cuộc đời tạm bợ mà!

Thường trong lòng chúng ta luôn có hai hạng người khó quên: Một là những người mình thương; hai là những người mình ghét. Nên sau khi chết sẽ gặp lại hai nhóm này. Thương gặp lại và ghét cũng gặp lại. Nên người biết tu phải xả hết giận hờn, không oán thù ai hết.

Thật ra chúng ta còn là phàm phu, bảo đừng giận thì chưa được, song có giận nên bỏ mau một chút. Kinh Phật có câu: “*Tăng hận bất cách túc”*, tức *Tăng giận không quá một đêm*. Chúng ta cũng giận khi nghe lời trái tai, nhưng giận một chút rồi bỏ để mai kia không gặp trở lại. Nếu ai ôm ấp giận hoài, đó là nguyên nhân để mai sau gặp lại. Chúng ta chấm dứt tâm oán hờn thì chúng ta được an vui.

*8. Ngũ ấm xí thạnh khổ*

Tức thân năm ấm này mạnh mẽ, hưng thịnh quá thì khổ. Ngược lại nếu chúng ta biết dùng thân năm ấm để tiến tu thì sẽ an vui. Tôi thường thí dụ như khi mình qua sông, không có thuyền bè, nhờ khúc gỗ mục mình lội qua sông. Khúc gỗ khi đó là hữu ích. Nhưng đã qua sông rồi phải biết bỏ khúc gỗ đi không nên tiếc.

Thân này cũng vậy, bệnh hoạn đau ốm đủ thứ, chúng ta lỡ mang vào rồi, phải dùng nó cho có ý nghĩa. Dùng thân làm lợi cho mình, đánh thức cho người, chỉ vì việc tiến tu thì đó là hữu ích. Còn nếu cung dưỡng săn sóc thân cho lắm, tới ngày nó mất thì khổ đau. Vì thương thân quá nên mất thân này liền tìm thân khác. Nhiều khi chụp được thân tốt, cũng có khi chụp phải thân xấu. Vì vậy mà có sinh trong địa ngục, ngạ quỷ, súc sanh. Chúng ta nhớ đừng quý thân, mà chỉ lợi dụng nó để lợi ích cho chúng sanh, để mình tiến tu. Đó là người biết dùng thân. Đã biết dùng thân thì vui chớ không khổ.

Như vậy tám thứ khổ này không phải thật khổ. Chỉ khi chúng ta mê, chúng ta mới thấy thật khổ. Nếu chúng ta tỉnh giác thì không còn khổ nữa. Phật nói khổ để chúng ta thức tỉnh, thức tỉnh thì không còn khổ, mà là được vui. Trong kinh Niết-Bàn, đức Phật có dạy bài kệ:  
  
<div class="align-center">
Chư hành vô thường  
Thị sanh diệt pháp  
Sanh diệt diệt dĩ  
Tịch diệt vi lạc  
</div>
  
Dịch:  
  
<div class="align-center">
Các hành vô thường  
Là pháp sanh diệt  
Sanh diệt diệt rồi  
Tịch diệt là vui  
</div>
  
Hành nghĩa là tất cả các tướng có đi có lại, các sinh hoạt ở thế gian đều là vô thường, không bền lâu, nó thuộc pháp sanh diệt. Từ thân hành cho tới ý hành, cả hai đều thuộc về pháp sanh diệt. Tất cả các thứ sanh diệt lặng hết thì tịch diệt hiện tiền. Chỗ lặng lẽ đó chính là an vui. Chúng ta hiểu đạo lý, phải khéo ứng dụng tu như vậy.

Một, đừng chấp thân vô thường là thật. Hai, phải lặng tâm vô thường sinh diệt xuống, lúc đó chúng ta sẽ hết khổ được vui. Đối với người tu niệm Phật, phải niệm Phật cho nhất tâm. Khi tâm sinh diệt hết mới được sanh sang cõi Cực Lạc. Đối với người tu thiền, nếu tâm sinh diệt lặng thì định, do định nên trí tuệ phát sinh, ấy là vui.

Phật dạy chúng ta biết các hành đều vô thường, đều là pháp sinh diệt. Chúng ta đừng cố chấp, đừng luyến tiếc, đừng quá thương yêu, mà phải làm sao cho tất cả những thứ sinh diệt đó lặng hết, thì tịch diệt là niềm vui an lạc sẽ đến với chúng ta. Trong nội tâm của mình, nếu cứ lo nghĩ chuyện này chuyện kia dồn dập, lúc đó gương mặt mình héo xàu. Ngược lại, nếu tâm mình thơ thới, không có một niệm lo nghĩ nào hết, lúc đó gương mặt mình tự nhiên được tươi vui. Như vậy, cái sinh diệt lặng rồi thì tịch diệt *(nguồn vui)* hiện tiền. Nên người khéo tu lúc nào cũng tìm cách đưa tâm sinh diệt của mình đi đến chỗ lặng lẽ. Đó là nguồn an lạc lớn lao nhất của người tu.

Tóm lại, chúng ta tu Phật là vui hay khổ? Tu Phật là vui. Phật nói khổ để chúng ta tìm ra nguyên nhân của khổ và diệt khổ thì được an vui. Vậy đạo Phật bi quan hay lạc quan? Người không hiểu rõ đạo Phật nên đánh giá sai lầm, cho đạo Phật là bi quan, yếm thế. Người hiểu đạo Phật đúng đắn là người biết tìm về nguồn an vui, biết tìm về nguồn giải thoát chớ không phải khổ đau như người ta tưởng.

Mong rằng tất cả chư Tăng, Ni cũng như Phật tử sau khi nghe tôi giải thích, quý vị hiểu và ứng dụng tu được, thì xứng đáng là người xuất gia, xứng đáng là người cư sĩ chân chính, không còn bị các thứ khổ làm cho buồn bã, sầu bi. Như vậy là quý vị biết nhổ hết nhân đau khổ để rồi cùng nhau được an vui. Nhổ hết gốc đau khổ thì Ta bà biến thành Cực Lạc, còn gì phải trông chờ xa xôi.

Một lần nữa tôi mong quý vị nghe, hiểu, cùng tu và cùng được an vui.
