# Nguồn gốc của đạo Phật {- #nguon-goc-dao-phat}

<div class="align-right">
*Giảng tại Trường Hạ chùa Long An, 1998*
</div>

Hôm nay chúng tôi được duyên lành về đây, trước hết thăm chư Tăng trong mùa an cư, sau có vài lời muốn nói cùng chư Tăng Ni. Chúng tôi thường tự tuyên bố rằng tôi là kẻ nợ của Tăng Ni, nên trọn đời lúc nào tôi cũng canh cánh trong lòng nghĩ đến người tu xuất gia, muốn làm sao tạo duyên tốt cho tất cả Tăng Ni trên đường tu, mỗi ngày một tiến lên và tiến đúng đường lối của Phật đã dạy.

Tăng Ni chúng ta là người hy sinh cả một cuộc đời để tu. Nếu một đời tu không được kết quả gì thì thực uổng một kiếp hy sinh. Với Phật tử cư sĩ chúng tôi cũng lo nhưng ít hơn, quý vị tu bao nhiêu tốt bấy nhiêu, có mất việc đạo thì còn lợi ích việc đời chứ không như Tăng Ni. Tăng Ni là người hy sinh trọn vẹn đời mình cho sự tu hành để đi tới chỗ an vui giải thoát và sau đó dìu dắt chúng sinh cũng được như thế. Nếu chúng ta tu không ra gì thì sự hy sinh đó thật đáng thương, đáng tiếc.

Vì vậy chúng tôi bận tâm nhiều, nên chúng tôi đã nhận lời mời của chư Tăng, chư Ni ở các tụ điểm an cư trong thành phố về đây tiếp chuyện, nhắc nhở quý vị làm sao cho sự tu hành được kết quả như sở nguyện của mình. Đó là nguyện vọng của chúng tôi.

Hôm nay tôi nói chuyện với quý vị một đề tài: *“Chúng ta tu theo đạo Phật không khéo bị quên mất gốc”*. Tại sao chúng tôi lại đưa ra đề tài này? Bởi vì là người xuất gia, bắt buộc chúng ta phải phăng tìm nguồn gốc của đạo Phật, lấy đó làm nền tảng vững chắc cho đời tu, luôn luôn nương tựa vào đó, chớ không thể nào quên hay đi sai lệch được. Do đó chúng ta phải quay về tận nguồn gốc của đạo Phật, xem ai là người khai sáng đạo Phật và Ngài đã tu hành truyền bá như thế nào, mà Phật giáo còn mãi đến ngày nay? Chúng ta là hàng hậu học kế thừa nối tiếp, phải làm những gì xứng đáng là đệ tử của Phật. Đó là mục tiêu tôi nhắm đến.

Nói đến nguồn gốc của đạo Phật thì chắc rằng tất cả Tăng Ni đều biết đức Phật là một Thái tử ở Ấn Độ xuất gia đi tu, bỏ cả sự nghiệp thế gian để tìm đạo giải thoát. Khi đã đạt được đạo quả rồi Ngài truyền giáo cho đến tận ngày nay gần như cả thế giới đều biết. Như vậy lịch sử đức Phật ai ai cũng thuộc nhưng ở đây tôi muốn đặt lại câu hỏi: Tất cả chúng ta nhớ lại xem vì sao đức Phật đi tu? Đó là điều mà chúng ta phải phăng tìm tận cội rễ, tột căn nguyên. Chúng ta nương theo đó mà có một lối đi, một con đường tiến lên tu tới chỗ cứu kính.

Dĩ nhiên tất cả chúng ta không ai phủ nhận đức Phật đi xuất gia là vì chứng kiến được cảnh sanh, già, bệnh, chết. Lý do này hết sức quan trọng đối với đạo Phật. Tôi nhớ trong sử có kể đức Phật một lần thấy người già Ngài liền thức tỉnh. Người này già rồi mai kia ta cũng già. Thấy người bệnh, người chết, Ngài biết rằng rồi ta cũng phải bệnh, phải chết. Vì vậy nên Ngài mới băn khoăn, thao thức không yên được.

Người mê thấy cảnh già, bệnh, chết tưởng chừng đó là chuyện của ai chớ không phải là chuyện của mình. Tất cả quý Tăng Ni, Phật tử đã từng chứng kiến cảnh già, bệnh, chết hay chưa? Chắc chứng kiến nhiều lắm. Nhưng chứng kiến mà quý vị có tỉnh không? Hay là người kia già, người kia bệnh, người kia chết không có gì quan trọng đối với chúng ta. Đây là quan niệm hời hợt cho nên đức Phật bảo chúng sanh si mê.

Đức Phật thấy người già, người bệnh, người chết Ngài liền tỉnh ngộ ta cũng sẽ như vậy, đó là việc chung chớ không phải việc riêng. Ngài nghĩ rằng đã có sanh ra rồi phải già, bệnh, chết. Lớp trước đã đến, lớp sau sẽ đến, ai cũng đến đó. Chẳng lẽ chúng ta sanh ra ở đời để chờ đến một ngày chôn vùi dưới đất hay sao? Chúng ta phải làm sao thoát ra khỏi luật vô thường chi phối con người như thế. Vì vậy đức Phật không kham chấp nhận cái già chết đến với Ngài, phải làm sao để thoát ra khỏi nó. Đó là lý do, mục đích mà Ngài đi tu.

Do đó khi đi tu gặp các vị tiên dạy, nào là pháp Tứ thiền, pháp Tứ không v.v… các pháp đó Ngài đã đạt được nhưng vẫn chưa thoát khỏi sanh, già, bệnh, chết nên Ngài từ giã họ ra đi. Sau đó đức Phật tu khổ hạnh vì nghĩ rằng nếu tận lực tu khổ hạnh có thể đời mình sẽ đạt được mục đích giải thoát sinh tử. Qua mấy năm trời khổ hạnh, kết quả chỉ đưa Người đến chỗ kiệt quệ, té xỉu không còn sức lực nữa. Ngài thấy đó là một quan niệm sai lầm. Nếu càng khổ hạnh chỉ càng đưa đến cái chết chứ không cứu được mình, được người. Ngài liền từ bỏ khổ hạnh và đến cội Bồ-đề ăn uống trung hòa, tức ngày ăn một bữa và tọa thiền.

Dưới cội Bồ-đề *(Tất-bát-la)* Ngài lấy một ít cỏ trải tòa ngồi, khi trải cỏ xong, Ngài chỉ cây Tất-bát-la thệ nguyện rằng: *“Ta ngồi dưới cội cây này nếu không đạt được đạo thì dù xương tan thịt nát cũng không rời khỏi nơi đây”*. Vì có lời thệ nguyện mãnh liệt đó nên suốt bốn mươi chín ngày đêm thiền định dưới cội Bồ-đề, Ngài liền được giác ngộ.

Nói đức Phật thành Phật là thành cái gì?  Đây là vấn đề chúng ta cần phải quan tâm. Khi Ngài ngồi tu dưới cội Bồ-đề đến đêm thứ bốn mươi chín, từ đầu hôm đến hết canh một Ngài chứng được Túc mạng minh. Túc là đời trước, mạng là sinh mạng, minh là sáng. Sáng ra được những việc trong nhiều đời nhiều kiếp về trước, tại sao Ngài sáng ra lẽ đó? Bởi khi Ngài đi tu, vì muốn giải thoát sinh tử nên Ngài đặt ra vấn đề: Trước khi ta có mặt ở đây ta là gì, ở đâu đến? Sau khi chết ta sẽ về đâu? Muốn dứt hết cội gốc sinh tử này ta phải làm sao? Đó là ba nghi vấn về số phận con người của Ngài.

Hiện giờ chúng ta có mặt ở đây nhưng trước kia chúng ta ở đâu, ta là gì? Khi thân này hoại chúng ta sẽ về đâu, còn hay hết? Muốn thoát ly sinh tử chúng ta phải làm sao, tìm cách gì để thoát ly sinh tử? Đó là ba nghi vấn tối quan trọng ai cũng thắc mắc. Khi đức Phật chứng được Túc mạng minh rồi, Ngài nhìn lui về quá khứ thấy vô số kiếp về trước Ngài đã từng làm gì, ở đâu, tu hành hạnh nào, có được những công đức gì v.v… nhớ rõ mồn một những việc đã qua.

Trong kinh A Hàm kể lại rằng, Ngài nhớ những sự việc cả muôn ức kiếp về trước như chúng ta nhớ những sự việc mới xảy ra hôm qua, hôm kia vậy thôi. Vì vậy khi chứng được Túc mạng minh rồi Ngài liền giải được cái nghi tại sao chúng ta có mặt ở đây, trước kia ta là gì. Ngày nay chúng ta đọc trong kinh Bổn sanh và Bổn sự kể lại cuộc đời đức Phật và cuộc đời các vị đệ tử của Phật, đó là do Phật chứng được Túc mạng minh, Ngài thuật lại để làm gương mẫu, nhắc nhở người sau tu. Đây là minh thứ nhất.

Tới canh ba Ngài chứng Thiên nhãn minh, thấy suốt được những vật hết sức nhỏ nhiệm, hết sức xa xôi, quá tầm thấy biết của người thường. Thấy rõ con người sau khi chết bị nghiệp dẫn đi luân hồi trong sáu đường. Trong kinh kể sau khi Phật chứng được Thiên nhãn minh, Ngài nói: *“Ta thấy chúng sanh đi trong luân hồi lục đạo như người đứng trên lầu cao nhìn xuống ngã ba đường, thấy kẻ đi qua, người đi lại một cách rõ ràng, không có nghi ngờ gì cả”*. Thế là Ngài giải được cái nghi vấn thứ hai, sau khi chết chúng ta đi về đâu. Chúng ta sẽ theo nghiệp lành, nghiệp dữ mà sanh trong cõi trời, cõi người *(lành)*, địa ngục, ngạ quỷ, súc sanh *(dữ)* chớ không phải hết.

Đây là một lẽ thật, do chứng Thiên nhãn minh mà Phật thấy được những việc nhỏ nhiệm vô cùng. Ngài thấy vô số vi trùng, Phật cách chúng ta hơn hai mươi lăm thế kỷ mà Ngài thấy được vi trùng. Vì vậy chư Tăng khi uống nước, nhất là nước không lọc, không nấu thì Phật dạy phải quán. Quán thế nào? *“Phật quán nhất bát thủy, bát vạn tứ thiên trùng v.v…”*. Phật nhìn trong bát nước có tám muôn bốn ngàn vi trùng. Ngày xưa Phật nói nước có vi trùng ai mà tin, vì con mắt phàm làm sao thấy!

Phật do thấy mà nói nhưng chúng ta không tin, nên biết cái thấy của Ngài với cái thấy của chúng ta khác xa vô cùng. Phật nhìn trong bầu hư không Ngài thấy vô số thế giới không thể tính kể, nên trong nhà Phật có từ hằng hà sa số thế giới không thể tính kể, nghĩa là thế giới nhiều như cát sông Gange ở Ấn Độ. Phật thấy trong bầu hư không này, những hành tinh như quả địa cầu của chúng ta nhiều không thể kể hết. Đó là minh thứ hai.

Đến khi sao mai vừa mọc Ngài bừng ngộ chứng được Lậu tận minh. Lậu là rớt, tận là sạch, nghĩa là sạch hết, không còn mầm rơi rớt trong sanh tử nữa, tức là không còn rơi lại trong tam giới lục đạo. Như vậy sau khi chứng được Lậu tận minh, Ngài đã đạt được mục đích giải thoát sanh tử. Ngài biết rõ nguyên nhân nào dẫn chúng ta đi trong luân hồi sanh tử và làm sao dứt sạch được nguyên nhân đi trong luân hồi sanh tử đó, đây gọi là chứng được Lậu tận minh. Khi chứng được minh này, đức Phật tuyên bố Ngài hoàn toàn giác ngộ, thành Phật.

Như vậy Phật thành Phật là do Ngài giác ngộ được nơi con người, biết được mình từ đâu đến, khi chết rồi sẽ ra sao về đâu, muốn dứt hết sanh tử phải làm cách nào, tu pháp gì. Ngài biết rõ hết những điều đó, Phật đã đạt được mục đích khi Ngài đi tu là giải thoát sanh tử. Sau khi chứng được Tam minh, Phật rất hoan hỷ vì đã đạt được mục đích.

Ngài nhớ lại những người bạn đồng tu với mình trước kia *(năm anh em Kiều Trần Như)* nên Ngài đi tìm những vị đó. Đến vườn Lộc Uyển gặp năm anh em Kiều Trần Như, Phật liền thuyết bài pháp Tứ đế. Đây là bài pháp nói về nguyên nhân đưa chúng ta đi trong sanh tử và làm sao chúng ta dứt được cội mầm sanh tử. Ở đây tôi chỉ nói đơn lược cho quý vị có khái niệm thôi, Phật dạy sở dĩ chúng ta có luân hồi sanh tử là do Tập đế. Từ Tập đế là nhân rồi đưa đến Khổ đế là quả, Tập đế và Khổ đế là nhân quả theo chiều luân hồi sanh tử. Làm sao chúng ta thoát ly được luân hồi sanh tử?

Phật dạy chúng ta ứng dụng phương pháp tu hành để diệt hết tập nhân, phương pháp diệt tập nhân là Đạo đế, diệt hết tập nhân rồi thì chúng ta được Diệt đế, Diệt đế là Niết bàn, thoát ly sanh tử. Những pháp đức Phật giác ngộ được trong đêm thứ bốn mươi chín nếu nói đủ thì rất nhiều, nhưng nói gọn trong Tam minh là Túc mạng minh, Thiên nhãn minh và Lậu tận minh. Tức Phật giác ngộ được ba vấn đề lớn mà Ngài đã thắc mắc về con người, gọi là giải thoát sanh tử.

Như vậy tất cả chúng ta không ai còn nghi ngờ gì nữa, đức Phật tu Thiền dưới cội Bồ đề được giác ngộ thành Phật và đem điều giác ngộ đó giáo hóa chúng sinh. Nghĩa là đức Phật nhân tu Thiền mà được giác ngộ. Do đó, sau khi Ngài thành Phật rồi, Ngài dạy đệ tử Tăng cũng như Ni đều tu Thiền mà chứng quả A La Hán. Trong kinh Pháp Cú, Phật dạy rằng: Hãy tu định, chớ buông lung. Tâm chớ mê hoặc theo dục. Đừng đợi đến khi nuốt hòn sắt nóng mới ăn năn than thở. Hoặc không có trí tuệ thì không có thiền định, không có thiền định thì không có trí tuệ. Người nào gồm đủ thiền định và trí tuệ thì gần đến Niết-bàn.

Như vậy quý vị thấy Phật răn các Tỳ-kheo phải tu thiền định, chớ buông lung, tâm đừng mê hoặc chạy theo ngũ dục, đừng đợi đến khi nuốt hòn sắt nóng mới ăn năn than thở. Lúc nào nuốt hòn sắt nóng? Là lúc xuống địa ngục. Nếu hiện đời chúng ta không chịu tu để sau khi chết đọa vào địa ngục, chừng đó than thở không kịp. Cho nên ngay bây giờ, trong lúc chúng ta đang khỏe mạnh, chúng ta còn đủ điều kiện để tiến tu, phải cố gắng tu đừng có chần chờ, sau này hối hận không kịp. Nhờ những lời dạy, lời răn đe đó nên các đệ tử đương thời của Ngài tinh tấn tu hành, chứng được quả A  La Hán rất nhiều. Đó là tôi nói những vị Tỳ-kheo trong thời đức Phật.

Kế đó nhìn lại lịch sử chư Tổ, chúng ta thường lạy Tây Thiên Đông Độ Việt Nam lịch đại Tổ sư, nghĩa là những vị Tổ sư từ Ấn Độ sang Trung Hoa đến Việt Nam, những Tổ sư đó tu pháp gì? Cụ thể nhất là bây giờ chúng ta hay thờ Tổ Đạt Ma. Ngài là vị Thiền sư thứ hai mươi tám ở Ấn Độ và là vị Tổ thứ nhất ở Trung Hoa. Như vậy chư Phật tu Thiền được giác ngộ, chư Tổ cũng tu Thiền được thành Tổ, chư vị A La Hán tu Thiền mà thành tựu đạo quả. Vậy pháp tu Thiền nhất định là pháp gốc của đạo Phật rồi.

Về mặt giáo lý hệ Nguyên thủy có hai: Hệ A Hàm dịch từ chữ Phạn ra chữ Hán gọi là Agama, hệ Pali dịch từ chữ Pali sang chữ Việt gọi là Nikaya. Trong đó Bát chánh đạo nằm trong ba mươi bảy phẩm trợ đạo, thể hiện cụ thể nhất tinh thần tu Thiền, từ chánh kiến, chánh tư duy, chánh ngữ, chánh nghiệp v.v… cho tới chánh niệm, chánh định. Chánh niệm tức phải giữ tâm niệm chân chánh, ngay thẳng rồi đi tới chánh định. Về pháp ngũ căn, ngũ lực thì có năm điều: tín, tấn, niệm, định, huệ. Tín là lòng tin, tấn là tinh tấn, niệm là chuyên niệm, định là thiền định, cuối cùng huệ là đạt được trí tuệ. Như vậy các pháp theo hệ Nguyên thủy cũng nhắc chúng ta tu thiền định và trí tuệ là gốc.

Chúng ta hiện giờ học theo pháp Đại thừa *(ngày nay gọi là hệ Phát triển)* tu Lục độ: bố thí, trì giới, nhẫn nhục, tinh tấn, thiền định, trí tuệ. Trong đó, cuối cùng là thiền định và trí tuệ. Như vậy tất cả pháp của Phật từ hệ Nguyên thủy đến Phát triển đều lấy thiền định và trí tuệ làm căn bản chớ không thể nào khác hơn được, đó là cái gốc. Đây là vấn đề mà ngày xưa tôi đã nặng lòng, phải lo nghĩ nhiều.

Sau những năm tôi đi giảng tại các Phật học viện Huệ Nghiêm, Đại học Vạn Hạnh, tôi thấy rằng bao nhiêu sở tri mà tôi học được trong kinh tôi đã đem chỉ dạy cho Tăng Ni, những thứ đó chỉ là kiến giải bên ngoài, còn chứng nghiệm trên sự tu thì thực tôi không có thì giờ. Do đó nên năm 1966 sau khi dạy xong khóa học tại Phật học viện Huệ Nghiêm và ở Dược Sư rồi, tôi xin nghỉ dạy lên núi tu một thời gian. Khi lên núi tu tôi quyết tâm và thệ nguyện rằng nếu phen này không phát minh được điều gì mới, thà là tôi chết luôn trong thất chớ quyết không xuống núi. Do thệ nguyện đó mà thời gian tu tôi thấy thật sự có kết quả, tôi vui vẻ nên mở cửa thất. Bởi vì như tôi đã nói tôi là kẻ nợ của Tăng Ni nên điều gì tôi thấy hay, tôi làm thinh không được, tôi phải làm sao cho Tăng Ni cùng chia xẻ được điều đó. Cho nên dù chỉ qua một năm nhưng tôi thấy có những cái hay, những cái mới, tôi liền ra thất và lập Thiền viện Chân Không vào năm 1969. Đến năm 1971 chúng tôi khai giảng khóa đầu. Tôi cương quyết khẳng định, ngày xưa tổ tiên mình tu thiền ngộ đạo thì ngày nay mình tu thiền chắc chắn cũng sẽ ngộ đạo, chỉ có chúng ta siêng tu hay lười nhác không chịu tu mà thôi.

Ngày nay đa số các chùa hay nói câu này: *“Thời bây giờ là mạt pháp tu không tiến được, thôi chỉ một câu niệm Phật rồi chờ vãng sanh bên kia làm tôi tớ Phật A Di Đà khỏe hơn, chớ tu Thiền không tiến, không thể tu được”*. Nói thời mạt pháp tôi lại đâm ra nghi ngờ, trong kinh Phật có chia ba thời: chánh pháp, tượng pháp, mạt pháp. Chánh pháp là thời của đức Phật, một trăm người tu thì một trăm người chứng đạo vì đức Phật trực tiếp hướng dẫn. Kế thời đức Phật là thời tượng pháp, tức sau khi Phật nhập Niết-bàn, những vị đệ tử chứng quả A La Hán hướng dẫn một trăm người tu thì có chừng năm mươi người chứng. Sau một ngàn năm tới đời mạt pháp thì trong muôn người tu chưa có một người chứng.

Nhưng bây giờ tôi nhìn khác một chút, tôi cho rằng chánh pháp hay mạt pháp gốc ở con người chớ không phải thời gian. Ngày xưa đức Phật còn tại thế, khi Ngài giảng kinh Pháp Hoa có năm trăm thầy Tỳ-kheo thối tịch. Đọc sử kỹ quý vị thấy trong thời Phật còn tại thế, thỉnh thoảng cũng có các thầy Tỳ-kheo xin hoàn tục. Hoàn tục là tu không được, tu không được thì đối với những vị đó là thời mạt pháp, không luận vào lúc nào cả. Còn bây giờ thời mạt pháp nhưng ai cương quyết liều chết tu hành, quyết phải đạt đạo, phải có kết quả thì đối với những người ấy đây là thời chánh pháp. Chánh pháp hay mạt pháp gốc ở con người hơn là ở thời gian. Vậy mà chúng ta cứ lệ thuộc vào thời gian rồi buông xuôi, tự than đời mình mạt pháp, tu sơ sơ để gieo duyên. Ngày tụng hai thời kinh, tối xem ti vi cho đỡ buồn, niệm Phật chờ chết Phật đón về Cực lạc cho khỏe, cứ nhàn nhàn vậy thôi. Lỗi ấy là vì cứ nghĩ thời mạt pháp nên không nỗ lực.

Tôi thì ngược lại, đời mạt pháp khó tu ta phải nỗ lực cố gắng tu nhiều hơn bằng hai, bằng ba, nhất định chúng ta sẽ có kết quả không nghi. Cho nên đối với tôi đời mạt pháp không quan trọng, quan trọng chỗ phát tâm mạnh yếu của chúng ta. Vì thế khi truyền bá tu Thiền tôi cố gắng tuyên dương, cố gắng kêu gọi chư Tăng Ni cũng như quý Phật tử nhìn thật kỹ, thấy thật rõ cốt tủy của đạo Phật để chúng ta tu, không nên mặc cảm như tôi lúc trước.

Đến đây tôi muốn nói đến Phật giáo Việt Nam của chúng ta một chút. Chư Tổ Việt Nam ban đầu từ thế kỷ thứ hai, thứ ba mãi đến thế kỷ thứ mười chín, các Ngài lãnh đạo Phật giáo Việt Nam đều là Thiền sư hết, như ngài Khương Tăng Hội, Mâu Bác v.v… cho tới cuối thế kỷ thứ mười chín là Tổ Liễu Quán ở miền Trung đều là Thiền sư. Đất nước Việt Nam thời bấy giờ Tăng Ni tu Thiền và Thiền sư lãnh đạo Phật giáo. Chỉ từ cuối thế kỷ thứ mười chín qua thế kỷ hai mươi chúng ta mới chuyển sang Tịnh độ.

Như vậy trước kia chư Tổ Việt Nam đều tu Thiền, nên hiện giờ mỗi khi quý Hòa thượng tịch, chúng ta thường được nghe đọc tiểu sử quý Ngài thuộc dòng Lâm Tế chánh tông hoặc Lâm Tế gia phổ v.v… Vậy Lâm Tế là ai? Là một vị Thiền sư ở Trung Hoa lập ra dòng thiền Lâm Tế. Ngài ở vào đời Đường cách chúng ta khoảng một ngàn năm. Khi nói *“từ Lâm Tế”* tức là nối dòng Lâm Tế mà hỏi tổ Lâm Tế là người nào, tu pháp gì thì chắc chúng ta cũng không biết luôn.

Như vậy có thể nói từ đức Phật cho đến các đệ tử lớn của Ngài và chư Tổ sau này đều lấy tu Thiền làm căn bản. Rõ ràng gốc của đạo Phật là tu Thiền. Nếu chúng ta tu pháp khác cũng không ngại gì, nhưng đối với Thiền chúng ta cũng phải nghiên cứu, phải biết cho rõ ràng. Gần đây những lần được đi nước ngoài trở về tôi đều thấy rằng, người nước ngoài, nhất là người Tây phương hiện nay muốn nghiên cứu đạo Phật thì đa số nghiên cứu về Thiền, chỉ một số ít người đi theo Mật tông ở Tây Tạng. Vì sao vậy? Vì họ thấy được thiền định là cội gốc của đạo Phật, giới trí thức Việt Nam chúng ta cũng vậy. Khi họ muốn nghiên cứu Phật giáo họ cũng thích nghiên cứu tu Thiền. Thế nên hiện giờ chúng ta làm Phật sự, hướng dẫn Phật tử tu, dù chúng ta không tu Thiền, chúng ta tu Tịnh độ đi nữa cũng phải nghiên cứu về Thiền để hướng dẫn Phật tử hâm mộ tu Thiền đúng pháp, không làm mất tín tâm của họ.

Khi hiểu được Phật giáo Việt Nam ngày nay nối pháp các hệ phái từ thuở trước, mang tinh thần Thiền tông rất là đậm nét, chúng ta càng phải trân trọng, càng phải nghiên cứu nhiều hơn, sâu hơn. Chúng ta biết rõ rồi nếu tu theo thì tốt, còn không tu thì cũng giải thích cho mọi người không bị lầm. Điều này tôi mong tất cả chư Tăng Ni và Phật tử chịu khó nghiền ngẫm thật kỹ. Nếu không thì chúng ta nói tu theo đạo Phật mà gốc của đạo Phật là tu Thiền chúng ta lại không biết. Đó là chúng ta bị mất gốc.

Ngày nay trình độ văn hóa của xứ sở chúng ta ngày mỗi tiến, mỗi vươn lên. Đời của tôi hay của quý vị thế hệ kế tiếp do không đủ phương tiện, không được học nhiều nhưng con em của chúng ta hiện nay và mai kia học rất giỏi, biết nhiều hơn chúng ta. Nếu chúng ta không khéo chỉ dạy đạo Phật một cách sáng sủa, cao siêu thì con cháu chúng ta sẽ không theo đạo Phật mà chúng lại xem thường đạo Phật, đó là lỗi lớn của chúng ta. Vậy mong tất cả Tăng Ni gắng tu, gắng học để mai này chúng ta xứng danh lãnh đạo Phật giáo Việt Nam và hướng dẫn con cháu chúng ta thấu hiểu được Phật giáo một cách đúng đắn, sáng suốt.

Đó là mục đích mong mỏi của chúng tôi, cầu mong Tam Bảo gia hộ cho tất cả quý vị tinh tấn tu hành, thành tựu được ý nguyện của mình trên bước đường tu hành.
