# Nói chuyện với lớp giảng sư thành phố Hồ Chí Minh {- #noi-chuyen-voi-lop-giang-su}

<div class="align-right">
*Giảng tại Thiền viện Quảng Đức (Văn phòng II), 2000*
</div>

Cùng tất cả Tăng Ni giảng sư, hôm nay tôi được Ban Hoằng Pháp mời giảng giải cho quý vị một buổi. Đối với tôi giảng giải là trách nhiệm của người tu sĩ, chứ không phải việc bên ngoài. Lúc nào đủ duyên, tôi rất sẵn lòng, trừ trường hợp đặc biệt không thể đến được thì thôi.

Hôm nay tôi nói chuyện với tất cả Tăng Ni đề tài: Phật pháp là thuốc trị tâm bệnh cho chúng sanh. Đề tài này thật ra rất rộng, bởi vì nó bao gồm toàn bộ giáo lý Đại thừa cũng như Tiểu thừa của Phật giáo. Nhưng có thể tùy theo hoàn cảnh, thời gian tôi nói được bao nhiêu hay bấy nhiêu, quý vị theo đó lãnh hội được chừng nào tốt chừng ấy.

Trong kinh Phật thường dạy pháp của Phật là thuốc trị lành tâm bệnh của chúng sanh. Nếu chúng sanh có bệnh gì thì Phật dùng thuốc ấy để trị. Như vậy chúng sanh có bao nhiêu bệnh, Phật có bấy nhiêu thứ thuốc. Chúng sanh có tám muôn bốn ngàn phiền não trần lao thì Phật cũng có tám muôn bốn ngàn pháp môn.

Bởi vì để đối trị bệnh của chúng sanh nên Phật mới nói ra tất cả pháp, với mục đích dạy chúng ta học và tu. Khi tu học xong chúng ta đem pháp ấy tiếp tục chỉ dạy cho những người khác, đó là con đường hoằng pháp lợi sinh. Nói hoằng pháp lợi sinh, nhưng thực nghĩa của nó là dạy phương pháp cho chúng sanh trị lành tất cả tâm bệnh của họ thôi.

Thuốc của Phật trị cho chúng sanh hết bệnh và sống hoài không chết. Vì vậy nhập Niết-bàn gọi là vô sanh, mà không sanh thì làm gì có tử? Như vậy tu theo Phật để đi đến chỗ cứu kính là giải thoát sanh tử, vượt lên trên dòng sanh tử. Uống thuốc của đức Phật, chúng ta sống được bao nhiêu tuổi? Vô lượng tuổi, không thể tính đếm được. Nên nói đức Phật là Vua thầy thuốc *(Vô thượng y vương)*. Đó là nghĩa thứ nhất.

Nghĩa thứ hai, thầy thuốc thế gian trị bệnh cho người nhưng tới khi mình bệnh thì trị không được, phải nhờ bác sĩ khác trị. Đức Phật thì ngược lại, Ngài tu để trị lành tất cả bệnh của mình rồi, sau đó mới trị bệnh cho người khác. Đó là Ngài dạy pháp tu để chúng ta biết trị những tâm bệnh cho chúng ta. Nhờ trị tâm bệnh được lành nên chúng ta mới khỏi dòng luân hồi sanh tử.

Chúng ta thấy Phật dạy mình làm, dạy mình tu những gì Ngài đã đạt được. Ngài đã thoát khỏi sanh tử, nên mới dạy chúng ta tu để ra khỏi sanh tử. Rõ ràng Ngài đã tự cứu và cứu chúng sanh, còn thầy thuốc ở thế gian đã tự cứu không được, mà cứu người thì có giới hạn nào thôi. Như vậy khả năng của Phật xứng đáng là vua thầy thuốc rồi.

Phật là vua thầy thuốc, bây giờ quý vị là giảng sư thì quý vị sẽ là gì đây? Là một người quảng cáo thuốc của đức Phật hay là con vua thầy thuốc, cháu vua thầy thuốc? Là con cháu ông Vua thầy thuốc, chớ không phải thầy thuốc thường đâu. Như vậy quý vị mới thấy tầm vóc quan trọng của một người tu.

Tôi trước kia cũng từng làm giảng sư, giảng nơi này, nơi kia. Thời từ năm 1954 cho tới 1963 là những năm chúng tôi nằm trong Ban Hoằng Pháp Giáo hội Phật giáo miền Nam. Thật ra khoảng thời gian đó, chúng tôi đang học tại Ấn Quang, nhưng Hòa thượng Trưởng Ban Hoằng Pháp là Thầy của chúng tôi, bắt chúng tôi đi giảng khi còn học Trung học năm thứ hai, thứ ba. Một năm học có ba đợt nghỉ, đợt tết nghỉ một tháng, đợt đầu hạ nghỉ một tháng, đợt cuối hạ nghỉ một tháng. Mỗi tháng nghỉ đi giảng hết ba tuần, thành ra còn có mười ngày thôi. Tùy theo sự phân bổ của Ban Hoằng Pháp, chỗ nào cần thì chúng tôi đi. Nhớ lúc đó bốn huynh đệ chúng tôi trong Ban Hoằng Pháp, tôi là một, thầy Huyền Vi là hai, thầy Thiền Định là ba, thầy Từ Thông là bốn, thường được mời đi giảng nhất.

Khi đi hoằng pháp, mỗi người có một sở trường, không ai giống ai cả. Nên bây giờ giảng cho lớp giảng sư, tôi thấy rằng không thể nào đem một khả năng riêng, một nghệ thuật riêng của từng cá nhân, truyền đạt cho quý vị mà gọi là đủ được. Thời chúng tôi, thầy Huyền Vi giảng là ăn khách nhất, Vì sao? Vì thầy có những ưu điểm:

1.Thầy khéo chọc cười. Khi giảng mà thấy người ta hơi thiu thiu thì thầy kiếm chuyện nói cho người ta cười rộ lên, nhờ thế mà hết buồn ngủ, nên rất nhiều người thích. Đó là ưu điểm thứ nhứt.

2.Thầy có tài viết chữ Hán bằng tay trái. Khi nào cần dẫn danh từ chữ Hán, thầy bước xuống bảng cầm phấn viết bằng tay trái, lúc đó người ta chú ý theo dõi và rất thích thú. Đó là ưu điểm thứ hai.

3.Thầy chịu khó học ngoại ngữ, nhất là tiếng Phạn. Ví dụ nói Bồ-đề thì thầy thuộc chữ Bồ-đề, tiếng Phạn viết như thế nào. Thầy còn học cả chữ Anh, chữ Pháp nữa. Khi giảng tới từ đó, thầy nói chữ Phạn, rồi nói chữ Anh, chữ Pháp; người ta nghe say mê. Đó là ưu điểm thứ ba.

Ba sở trường của thầy Huyền Vi, tôi không được cái nào hết. Tôi không có tài chọc cười, tôi không biết viết tay trái và tôi cũng không học tiếng Anh, tiếng Pháp nữa. Nên tôi thua thầy những điểm đó.

Thầy Từ Thông thì có sở trường vẽ. Thầy nói con cò, liền quẹt quẹt vài cái là nhìn thấy con cò, nên người ta cũng chú ý. Riêng tôi, tôi không có sở trường nào cả. Tôi chỉ đào sâu vào đề tài mình giảng, cố gắng hết lòng cho người nghe lãnh hội vậy thôi. Nên so với quý thầy, tôi thuộc hạng trung bình.

Khi đi giảng, Giáo hội lại thường phân công đi chung hai, ba người. Người nào giảng ăn khách thì được mời hoài, còn người giảng dở thì có mặt mình cũng coi như bị quên. Vì vậy đi chung với người giảng giỏi buồn lắm. Nhưng tôi với thầy Huyền Vi có cái duyên đặc biệt, thầy giảng ăn khách nhưng có ai hỏi thì thầy để tôi trả lời. Thành ra hai chúng tôi hỗ tương nhau cũng được.

Như tôi đã nói, thời gian đi giảng thật ra là thời gian cắm đầu học ở trường. Học xong rồi đi giảng nên không có thì giờ tu. Thưa thật ngay cả hai thời công phu cũng không tu đủ nữa. Bởi vì học đâu có thì giờ mà tu. Cho nên thời gian đi giảng thấy Phật tử nghe vui, mình cũng mừng. Nhưng có một lần chúng tôi giảng Phật Học Phổ Thông khóa II ở Rạch Giá, Phật tử đông lắm. Tôi còn nhớ rõ, kỳ đó chúng tôi giảng về quả vị tu chứng của Tứ quả Thanh văn. Giảng xong, về chỗ nghỉ. Tôi và thầy Huyền Vi đang ngồi uống nước, thì có một Phật tử tới đảnh lễ hết sức tha thiết, ông nói:

\- Quý thầy giảng về quả vị tu chứng của Tứ quả Thanh văn, tụi con nghe rất hay. Nhưng thưa thầy, thầy đã chứng được quả nào rồi?

Tôi ngẩn ngơ, không biết nói sao. Lúc đó thầy Huyền Vi lanh miệng hơn tôi, liền trả lời:

\- Đạo hữu không biết sao, trong nhà Phật thường nói ai tu chứng thì nấy biết, như uống nước lạnh nóng tự biết, làm sao nói được?

Nghe vậy, Phật tử ấy không hỏi nữa. Nhưng kể từ đó tôi thật áy náy, không hài lòng về mình chút nào cả. Tôi thấy mình chỉ là người quảng cáo thuốc của Phật, chớ thực sự không phải thầy thuốc con.

Từ đó tôi cứ ôm ấp một nỗi buồn trong lòng. Cho tới sau này khi mở Phật Học Viện Huệ Nghiêm, tôi tự hứa với lòng rằng dạy một khóa cho anh em ra trường rồi, tôi sẽ xin nghỉ để tu một chút. Chớ thực ra thời gian qua vừa học, vừa đi dạy không có thì giờ tu. Nên mãn khóa của anh em ở Huệ Nghiêm và quý cô ở Dược Sư rồi, tôi xin phép nghỉ, giao lại cho thầy Bửu Huệ trông nom trường, tôi lên núi Vũng Tàu để tu.

Tôi tự nghĩ tất cả những nỗi niềm khắc khoải của mình, nói thì hay mà hỏi đến việc tu thì không biết, không có gì cả, như vậy quả tang mình chỉ là một tay quảng cáo thôi. Phật nói pháp này hay, pháp kia hay mình đều biết hết, nhưng hỏi thầy có lành bệnh chưa thì lắc đầu không dám nói. Đó là một khuyết điểm lớn mà tôi tự thấy. Nhưng vì hoàn cảnh ngày xưa, Phật pháp quá cần nên chúng tôi không dám từ chối. Mấy huynh đệ hiện nay có lẽ khỏe hơn, lúc nào học xong rồi mới đi giảng. Hoặc ai muốn chuyên tu một thời gian cũng có thể được.

Từ khi nhập thất tu và tu có được chút ít tiến, tôi mới thấy vui, thấy hài lòng phần nào. Những gì mình nói được, mình cũng biết rõ, nắm chắc không nghi ngờ nữa. Cho nên ngày xưa tôi giảng thường thôi, không ăn khách lắm, nhưng tu một thời gian rồi giảng trở lại, thì Phật tử tới rất đông. Như vậy sau này Phật tử tới đông, không phải tôi có nghệ thuật nói hay, chọc cười khéo mà chẳng qua là tôi tu, tôi biết được lẽ thật của đạo ra sao thì chỉ dẫn cho mọi người cùng tu theo như vậy, nên họ chịu nghe.

Người ta chịu nghe là đến với mình, mình biết dạy họ giáo lý và biết chỉ phương pháp cho họ tu, nên họ mới hoan hỷ. Chớ nếu nghe rồi về, khi hỏi cách tu lại không biết, như vậy Phật pháp đối với họ không hữu hiệu. Mà đã không hữu hiệu thì người ta theo làm gì nữa.

Như năm 1964 tôi có mặt trong kỳ Đại hội Phật giáo năm ấy, tôi đề nghị với quý Hòa thượng rằng, Phật giáo Việt Nam có ba tông phái chánh là Thiền, Tịnh, Mật. Nhưng bây giờ không có tông phái nào đủ cơ sở để hướng dẫn cho Tăng Ni, Phật tử tu. Vậy xin quý Hòa thượng cho thành lập Thiền viện, Tịnh viện, Mật viện; mỗi nơi có một phương pháp chuyên môn để tu hành.

Như thế khi giảng sư đi giảng, ai muốn tu Thiền thì giới thiệu tới Thiền viện, ai muốn tu Tịnh giới thiệu tới Tịnh viện, ai muốn tu Mật giới thiệu tới Mật viện. Bởi khi giảng, giảng sư chỉ quảng cáo thuốc thôi, ai muốn mua thuốc phải đến xí nghiệp sản xuất thuốc mới mua được. Chúng ta phải có chỗ để giới thiệu, hành giả muốn tu theo pháp môn nào thì đến nơi đó, sẽ được chỉ dẫn cặn kẽ hơn.

Nhìn lại Phật giáo chúng ta không có chỗ nào chuyên hết. Mình nói pháp đó hay lắm, cao siêu lắm, nhưng Phật tử hỏi tu làm sao, thầy dạy cụ thể cách thức thực tập thì thầy cũng ngẩn ngơ. Như vậy có phải là một khuyết điểm lớn trong tổ chức của mình không?

Bởi vậy thời của tôi, tôi thấy rất rõ một số cư sĩ học Phật cũng kha khá như ông Nhuận Chưởng, ông Minh Đăng… các đạo hữu học cũng lâu ở Ấn Quang, có thể giảng được. Vậy mà sau này, ông Nhuận Chưởng thì theo ông địa, bà mẫu nào đó. Còn ông Minh Quang bỏ Phật giáo, tu theo đạo Ba Hai bên Ấn Độä. Tại sao vậy?

Mới nhìn chúng ta nghĩ những người đó phản bội, nhưng sự thực không phải vậy. Vì họ đã hiểu phần lý thuyết rồi, họ chỉ cần tu thôi, nhưng ai dạy họ tu đây? Chùa nào cũng tu một cách chung chung, không có chỗ chuyên môn, không có nơi nghiên cứu và thực tập đến nơi đến chốn, thì làm sao chúng ta giới thiệu cho họ tu? Mà không có nơi tu tức là không đáp ứng được nhu cầu tâm linh của họ. Do đó, buộc lòng họ phải đi tìm nơi này kiếm nơi nọ, vô tình lạc vào những nẻo tà. Đó là một khuyết điểm lớn của Phật giáo chúng ta.

Cho nên khi chuyên tu, tôi mới thấy được lợi ích lớn lao của đạo. Vì sở trường của tôi tu Thiền nên tôi thành lập các Thiền viện. Còn Tịnh viện và Mật viện, tôi chưa thấy được mô hình nào cụ thể, đi vào chuyên môn của pháp ấy một cách rõ ràng cả.

Như vậy một giảng sư chỉ nói pháp cho Phật tử nghe, hiểu nhưng bản thân chưa có điều kiện thực hành, thì tự nhiên mình chỉ là một quảng cáo viên thôi, đâu phải thầy thuốc chính hiệu. Giá trị Phật pháp sẽ được mở rộng hay bị tiêu mòn? Đó là vấn đề mà tôi muốn đặt ra cho tất cả quý huynh đệ hiểu và nghĩ tới tương lai của Phật giáo.

Chúng ta tu Phật, nhất là những thầy thuốc con phải biết những điều gì?

Một là phải biết thuốc.

Hai là phải biết bệnh.

Ba là phải biết liều lượng cho người uống khỏi bệnh.

Ngày xưa Tôn giả A Nan tuy ở gần đức Phật, nhưng công phu tu tập vẫn chưa xong. Một hôm có  hai người đệ tử đến xin Ngài hướng dẫn tu. Ngài dạy người thợ rèn quán bất tịnh, người giữ mồ mả quán sổ tức. Hai ông tu một thời gian, không có kết quả gì hết. Họ đến bạch với Ngài: “Con tu lâu quá mà không có kết quả, như vậy là tại sao?” Ngài lúng túng không biết lý do, nên cầu cứu với Phật:

\- Bạch Thế Tôn, con có hai người đệ tử xin dạy pháp tu, một người con dạy quán sổ tức, một người con dạy quán bất tịnh mà họ tu hoài không có kết quả. Xin Thế Tôn dạy con phải làm thế nào để giúp cho họ tu có kết quả.

Phật hỏi:

\- Người ông dạy quán bất tịnh làm nghề gì?

\- Bạch Thế Tôn, họ làm thợ rèn.

Hỏi:

\- Người ông dạy quán sổ tức làm nghề gì?

\- Bạch Thế Tôn, họ làm nghề giữ mồ mả.

Phật nói:

\- Ông dạy như vậy là sai rồi. Người giữ mồ mả ở nghĩa địa xem thấy thây ma hoài, dạy quán bất tịnh mới thành công. Còn người thợ rèn thổi ống bễ phì phịch phì phịch, dạy quán sổ tức mới thành công.

Nghe nói vậy Ngài biết mình dạy sai, nên trở về dạy hai người đệ tử đúng như lời Phật dạy. Thời gian sau, hai người ấy vui mừng thưa: *“Con vâng lời Thầy dạy nên tu rất có kết quả”*.

Đó, thầy thuốc mà không biết bệnh, trường hợp nào nên uống thuốc gì, nếu dạy sai đi thì không có kết quả. Đến trường hợp uống thuốc lặm nữa. Uống thuốc lặm là như đức Phật dạy các thầy Tỳ-kheo quán bất tịnh, khi quán bất tịnh các thầy thấy thân nhớp nhúa, gớm đến không thể sống nổi, nên huynh đệ rủ nhau cùng cắt cổ chết hết. Đến ngày Bố-tát Phật thấy chỉ còn bảy tám người, Ngài hỏi nguyên do, mới hay sự việc trên. Phật liền quở:

\- Ta dạy quán bất tịnh là cốt để trị bệnh đắm sắc, chứ không phải quán bất tịnh để tự tử. Tu mà tự tử là sai lầm rồi.

Vì vậy trong kinh nói sau khi quán bất tịnh, thấy nhờm gớm thân này đến rởn óc thì phải dừng, quay sang quán tịnh. Đó là trị bệnh mà uống quá liều thì cũng chết. Chúng ta là thầy thuốc phải biết thuốc, biết bệnh và biết liều lượng cho uống thì bệnh mới lành. Nếu không biết những điều đó thì chẳng những trị không lành bệnh mà có khi còn tai hại hơn nữa.

Tôi xin hỏi các thầy thuốc con ở đây, như có người mắc bệnh tham đến xin điều trị, quý vị dạy phương thuốc nào? Đó là thực nghiệm mà chúng ta phải biết. Đã là thầy thuốc thì phải biết thuốc, biết cách trị bệnh cho có hiệu quả. Khi người ta khai bệnh tham, chúng ta đừng vội dạy pháp liền. Bởi vì tham có tới năm thứ thông dụng: tham tài, tham sắc, tham danh, tham thực, tham thùy hoặc tham sắc, tham thinh, tham hương, tham vị, tham xúc. Trong năm cái tham đó, dùng thuốc khác nhau hay là cùng một thứ? Điểm này thầy thuốc cần phải biết.

Người tham tài muốn có tiền của nhiều, tới xin thầy dạy phương pháp tu cho hết tham thì chúng ta phải dạy pháp bố thí. Bố thí là sao? Như gia đình mình mỗi tháng có một triệu đồng đủ sống, bây giờ tháng này làm được một triệu hai, như vậy là dư hai trăm. Một triệu đã đủ sống, còn dư mà muốn để dành là tham. Nếu dư hai trăm để dành, tháng sau dư hai trăm cũng để dành nữa, tích lũy như vậy đó là tham. Muốn dứt lòng tham thì dư hai trăm, tìm xem ai nghèo đói giúp họ, đó gọi là bố thí. Dư hai trăm liền bố thí thì còn tham không? Hết tham. Như vậy bố thí là trừ bệnh xan tham. Pháp nào trị bệnh nấy rõ ràng.

Nếu người khai bị bệnh tham sắc dục thì chúng ta dạy quán bất tịnh để trị. Khi quán sát thân này thấy ba mươi sáu vật trong thân đều nhơ nhớp. Hoặc như thân người chết rã rời, nhớp nhúa, quán như vậy sẽ hết bệnh tham dục. Nhớ tới thân đã gớm còn đắm sắc gì nữa?

Nếu người bị bệnh tham danh, chúng ta dùng hai phương thuốc trị mới lành. Phương thuốc thứ nhất là quán vô thường, nghĩa là danh được rồi sẽ mất chứ không còn hoài. Ví dụ như người đắc cử một chức vụ nào đó, khi mãn nhiệm kỳ bốn năm tám năm rồi cũng trở lại thường dân, chứ đâu ngồi mãi chiếc ghế đó được. Như vậy giành giựt nhau, tranh đấu nhau để có một chút chức tước, nhưng chức tước đó được rồi sẽ mất. Vì mất nên nói không lâu dài. Đã không lâu dài thì tội gì mình phải khổ, phải lo. Đó là thang thuốc quán vô thường, nhưng một thang này thôi thì chưa đủ hiệu nghiệm, phải thêm thang thuốc quán khổ nữa.

Khổ là sao? Đức Phật dạy người hiếu danh khi chưa được thì chạy chọt, tìm cách cho được nên khổ. Khi được rồi thì sợ mất nên cũng khổ. Khi đã mất càng buồn rầu càng thêm khổ. Như vậy chưa được khổ, được rồi khổ và mất cũng khổ. Ba thời, trước khổ, giữa khổ, sau cũng khổ. Xét như vậy thì hết tham danh.

Nếu người bị bệnh tham ăn, chúng ta dùng thuốc gì để trị? Bệnh này rất phổ biến. Bởi vì ai cũng thích được ăn ngon, ăn nhiều. Nên muốn trị bệnh tham ăn phải dùng pháp quán bất tịnh. Tại sao phải quán bất tịnh? Vì khi thức ăn còn ở ngoài, trước mắt trước mũi, mình ngửi nghe thơm tho nhưng khi nhai nuốt tới cổ rồi thì nó còn ngon, còn thơm nữa không? Nếu tới bao tử mà bao tử không chịu chứa, bắt phải ụa ra. Khi ụa ra có gớm không? Nếu nó sạch, nó quý thì trong ngoài gì cũng sạch, cũng quý. Tại sao trong bụng mình mửa ra thì gớm thôi là gớm. Còn như tiêu hóa được, xuống dưới rồi cho ra cửa sau có gớm không? Rất là gớm. Như vậy nếu nó sạch thì trước, giữa, sau đều sạch. Đằng này chỉ một chút bên ngoài thôi, vô tới bên trong là bắt đầu nhớp nhúa, rồi khi trả ra cũng nhớp chớ đâu phải sạch. Cái không sạch mà tại sao mình tham? Đó, như vậy nghĩ tới nhơ nhớp mà bớt bệnh tham ăn.

Đồng thời phải nghĩ tham ăn là gốc của khổ vô thường. Tại sao? Bởi vì nuốt vô khỏi cổ thì tất cả thức ăn mất hết, chỉ ngon có mấy phút thôi. Nói mấy phút là nhiều đó, chớ còn thật ra một miếng ăn ngon chỉ có mấy giây đồng hồ. Cái ngon đó không thật, chỉ giả tạm, qua rồi mất. Nó là vô thường, vô thường thì có gì mà mình phải tham? Như vậy nhờ quán thức ăn bất tịnh, vô thường nên trị được bệnh tham ăn.

Nếu người bị bệnh tham ngủ, dùng thuốc gì để trị? Tham ngủ là gốc của si mê, lười biếng. Nên muốn trị bệnh này phải lấy cây roi tinh tấn mà đánh nó. Nghĩa là khi nghe tiếng kẻng phải trỗi dậy liền, nếu chần chờ là lười biếng. Người như vậy rất xấu hổ, không nên, phải thức đúng giờ giấc để tu tập. Do đó phải thúc nó bằng roi tinh tấn, kêu dậy lo tu. Chỉ có tinh tấn mới đuổi được con ma tham ngủ thôi.

Đồng thời trong nhà Phật cũng dạy lấy thuốc vô thường để trị bệnh tham ngủ. Bởi vì cuộc đời chúng ta không lâu dài, vô thường, không đoán định được. Bao nhiêu tuổi mất, không ai biết được. Một ngày qua tức tuổi thọ giảm một phần. Như vậy nếu để ngày này trôi qua, ngày kia trôi qua thì đời tu của mình còn có giá trị gì? Muốn sống có ý nghĩa, chúng ta phải nhớ đời là vô thường, ngày nào còn sống thì chúng ta cố gắng tu ngày ấy.

Như trong kinh có câu: *“Thị nhựt dĩ quá, mạng diệc tùy giảm, như thiểu thủy ngư, tư hữu hà lạc. Đại chúng đương cần tinh tấn, như cứu đầu nhiên. Đản niệm vô thường, thận vật phóng dật”*. Nghĩa là *ngày nay đã qua, mạng theo đó mà giảm, như cá cạn nước, không có gì vui hết*. Đại chúng cần phải tinh tấn tu, như cứu lửa cháy đầu. Chỉ nhớ nghĩ vô thường, dè dặt chớ buông lung! Đó là dùng thuốc quán vô thường để thúc đẩy mình. Nhờ thế trị được bệnh tham ngủ.

Đó là những phương thuốc trị bệnh tham.

Bây giờ có người bị bệnh sân đến xin thuốc, chúng ta sẽ dạy họ trị bằng cách nào? Trong nhà Phật dạy rất đầy đủ, người bệnh sân phải dùng thuốc nhẫn nhục và từ bi để trị.

Muốn nhẫn nhục phải làm sao? Khi người ta chọc mình nổi tức lên, muốn nhịn được họ chúng ta phải đọc câu này: *“Nhịn là khôn, nói là dại”*, nhắc đi nhắc lại chừng một chục lần thì hết nói. Hết nói thì tránh được lỗi sân hận. Vì khi nổi nóng thì thường nói bậy, làm khổ người ta. Nói bằng lời chưa đã thì tới tay chân. Cho nên vừa sửa soạn nói thì tự nhắc mình: *“Nhịn là khôn, nói là dại”*, từ từ  sự nóng giận chìm xuống. Nhưng chìm xuống chứ chưa hết gốc đâu, lâu lâu nhớ lại cũng nổi giận nữa. Nên phải dùng quán từ bi để trị cho dứt gốc.

Quán từ bi là thương từ người thân như cha mẹ, anh em cho tới người sơ như những kẻ lạ và cuối cùng là người thù, mình đều thương hết. Chừng nào thương được người thù thì không còn sân nữa. Đó là bứng tận gốc.

Như vậy mỗi một bệnh, chúng ta phải dùng một hoặc hai pháp hỗ tương để trị thì bệnh mới lành. Bệnh nào dạy pháp ấy, trị được lành thì bệnh nhân mới được an lạc. Còn mình dạy nhiều pháp nhưng ai muốn tu gì thì tu, chứ mình không chỉ rõ pháp nào trị bệnh ấy, thì việc tu sẽ không đến nơi đến chốn. Đó là tôi nói đại lược về bổn phận của một ông thầy thuốc.

Kế đây tôi nói thêm, một vị giảng sư còn phải nắm vững hai yếu tố. Hai yếu tố ấy là gì?  Một là khế lý, hai là khế cơ. Khi giảng phải hợp với chánh pháp là khế lý, hợp với trình độ của người đương thời là khế cơ. Có khi chúng ta soạn bài giảng cao, nhưng tới chỗ giảng thấy toàn căn cơ thấp thì chúng ta phải hạ xuống cho hợp với căn cơ của họ. Ngược lại, nếu mình soạn bài thấp mà tới chỗ giảng thấy toàn căn cơ cao, thì mình phải nâng nội dung bài giảng lên cho phù hợp. Vì vậy hai yếu tố khế lý, khế cơ là tối quan trọng đối với một giảng sư. Giảng sư mà không biết điều này thì dễ thất bại. Đó là điều quý vị cần nhớ.

Khi nói đến khế cơ thì phải thấy được hai phần: một là thời cơ, hai là căn cơ. Thời cơ tức là thời điểm mình giảng trong hoàn cảnh xã hội như thế nào, thích hợp hay không? Căn cơ là trình độ người nghe tới đâu, phải nói cho khế hợp. Được vậy mới gọi là người lịch lãm trong việc giảng dạy. Nói thế để quý vị thấy hoàn cảnh là yếu tố cần thiết cho chúng ta nhận xét và ứng dụng một cách thích hợp cho sự tu hành.

Về thời cơ, chúng ta cứ nhìn suốt chiều dài lịch sử Phật giáo Việt Nam, bắt đầu từ thế kỷ thứ thứ hai mãi tới bây giờ gần hai mươi thế kỷ. Nhưng từ thế kỷ thứ chín, thứ mười là thời Việt Nam giành độc lập từ tay người Trung Hoa. Thời đó, Phật giáo Việt Nam chủ yếu là tu Thiền. Thiền theo hai hệ: Hệ của ngài Tỳ Ni Đa Lưu Chi và hệ của ngài Vô Ngôn Thông. Hai hệ đó truyền sang Việt Nam thì các nơi đều lấy Thiền làm nền tảng cho việc tu hành. Nên các nhà sư giúp cho đất nước được độc lập toàn là Thiền sư, như Thiền sư Vạn Hạnh, Thiền sư Khuông Việt… Các Ngài đảm đang trách nhiệm hướng dẫn cho triều đình sống và trị nước hợp với đạo lý. Đến hai tông phái Lâm Tế và Tào Động từ Trung Hoa truyền sang Việt Nam vào thế kỷ thứ 18, 19 cũng tu Thiền. Như vậy từ trước mãi cho đến thế kỷ 19, Phật giáo Việt Nam gần như là Phật giáo tu Thiền.

Nhưng tới thời Pháp thuộc, trong thế kỷ 20 thì không tìm ra được người tu Thiền. Tại sao như vậy? Điều đó cũng dễ hiểu thôi. Bởi vì cuối thế kỷ 20 là thế kỷ chúng ta bị Pháp cai trị, nền độc lập của xứ sở không còn. Nếu còn chỉ ẩn kín nơi một số người làm cách mạng. Vì vậy đa số đều thất vọng khi thấy mình bị làm tôi đòi, nô lệ. Mà đã nô lệ thì tu Thiền không thể thích hợp được. Cho nên từ đó trở về sau các bậc Tôn túc đã khéo léo, chuyển từ pháp Thiền qua pháp Tịnh độ.

Như vậy pháp tu Tịnh độ lúc đó tương ứng với hoàn cảnh đất nước bị Pháp cai trị. Bởi vì bản thân người dân không có gì vui, mà luôn cảm thấy mình bị nô lệ nên buồn chán. Tụng kinh Di Đà thấy cõi Cực Lạc ở Tây phương rất vui đẹp, nên ai cũng mong mỏi được sống trong cảnh an lạc đó cả. Vì vậy pháp môn niệm Phật cầu vãng sanh thích hợp với hoàn cảnh lúc đó. Các Ngài dạy tu Tịnh độ đều được mọi người hưởng ứng tu theo. Lý do ấy rất rõ ràng.

Nhưng tới ngày nay, đất nước đã hoàn toàn độc lập, chúng ta thấy tu Thiền thích hợp trở lại. Quý vị đừng nghĩ tôi tu Thiền nên chủ quan cho rằng Thiền là hay hơn cả. Tôi nhắc lại cho quý vị nhớ, nhà nước hiện giờ luôn nhắc nhở toàn dân phải xây dựng lại nền văn hóa mang bản sắc dân tộc của mình. Muốn cho văn hóa Việt Nam thể hiện đầy đủ bản sắc dân tộc thì Phật giáo chúng ta phải làm sao? Nếu chúng ta giữ như ngày xưa, tối thì Tịnh độ niệm Phật tụng kinh Di Đà, khuya thì trì chú Lăng Nghiêm. Như vậy có thích hợp với bản sắc dân tộc không? Vì tụng kinh Di Đà bằng chữ Hán rồi trì chú bằng chữ Phạn. Hai ngôn ngữ đó người Việt Nam nghe không ai hiểu cả.

Như vậy người Việt Nam tu và dạy cho Phật tử mình tu mà không ai hiểu gì hết, thế là sao? Điều đó hết sức vô lý. Nếu chúng ta muốn thích ứng, hài hòa giữa đời với đạo thì phải có pháp tu thích hợp với hoàn cảnh xã hội hiện tại. Nhất là giảng sư đi đâu cũng nói, cũng chỉ cho người ta cái gì đúng, cái gì sai, cái gì hợp, cái gì không hợp v.v... mà bản thân chúng ta thì không có đường lối tu thích hợp.

Như bây giờ chúng ta tu hay dạy người tu, mà pháp môn ấy không thích ứng với bản sắc dân tộc, tinh thần dân tộc hay văn hóa dân tộc thì đó là không hợp thời rồi. Cho nên thay vì tụng hai thời Tịnh độ và trì chú Lăng Nghiêm, chúng tôi chỉ dạy Phật tử tụng sám hối sáu căn của vua Trần Thái Tông soạn. Như vậy có phải gần với dân tộc hơn không? Vì đó là nghi thức của người Việt Nam soạn. Một bài sám hối mang tính chất hoàn toàn của người Việt Nam. Còn các bài sám hối khác, văn tuy hay nhưng là của người Trung Hoa soạn ra, làm sao gần gũi với người Việt Nam được.

Kế đó, chúng tôi chủ trương khôi phục Thiền tông đời Trần. Năm ra Bắc, tôi được Viện Hán Nôm mời nói chuyện ba buổi. Trong ba buổi nói chuyện ấy, quý vị có đặt một câu hỏi: Nếu nói Thiền Việt Nam thì phải có những nét khác Thiền Trung Quốc, Thiền Nhật Bổn, Thiền Ấn Độ… Như vậy thì thế nào là chỗ đặc thù của Thiền Việt Nam?

Ở đây, tôi xin đi xa một chút cho quý vị hiểu rõ. Ngày nay chúng ta nghe gọi Phật giáo Việt Nam, trong đó Phật giáo là chung còn Việt Nam là riêng. Phật giáo là chung, gốc đó không sai nhưng ngọn có sai biệt chút ít, điều này không thể tránh khỏi. Như vậy Phật giáo Việt Nam với Phật giáo Trung Hoa, Phật giáo Nhật Bổn, Phật giáo Thái Lan v.v... mỗi nơi đương nhiên phải có nét riêng khác. Gốc đạo lý thì không hai nhưng ứng dụng tu hành cho phù hợp với từng dân tộc thì có sai biệt. Cho nên câu hỏi Thiền tông Việt Nam so với Thiền Nhật Bản, Trung Hoa, Ấn Độ sai biệt ở chỗ nào, không phải là vấn đề đơn giản.

Trong phạm vi bài này, tôi không thể nói đầy đủ hết được, nên chỉ tóm lược cho quý vị có khái niệm thôi. Đặc thù Phật giáo Thiền tông ở Ấn Độ là lý luận rất siêu thoát, rất tinh vi. Còn Trung Quốc, họ luôn quan niệm và tự hào mình là một nước nằm giữa thế giới nên có nền văn hóa cổ xưa nhất trần gian. Cho nên Thiền tông Trung Quốc, nhất là cuối đời Đường sang đời Tống, có những biến chế, sáng tạo một cách đặc biệt. Như ở Ấn Độ thì lý luận khúc chiết, còn Trung Quốc thì Thiền được thể hiện bằng đánh, bằng hét v.v... Chúng ta nghe Tổ Hoàng Bá hay đánh, Tổ Lâm Tế hay hét cho tới ngài Đức Sơn thì ăn gậy v.v... là những điểm đặc biệt của Thiền Trung Quốc.

Thiền tông Nhật Bổn thì sao? Không đánh, không hét như Trung Quốc mà Nhật Bổn nặng về nghệ thuật. Cho nên Phật giáo ở đây đều biến thành nghệ thuật hết, như nghệ thuật bắn cung, nghệ thuật đánh kiếm, nghệ thuật đánh võ. Vì vậy về võ thì gọi là Nhu đạo, về kiếm gọi là Kiếm đạo, về trà gọi là Trà đạo.

Đó là những sai biệt của Thiền tông Ấn Độ, Trung Hoa, Nhật Bổn. Còn Việt Nam chúng ta thì sao, có gì đặc biệt?

Thiền tới Việt Nam là một nước nhược tiểu, cho nên lúc nào cũng có tính chất khiêm nhường. Nhưng người đã lãnh hội được Thiền thì có cảm hứng đặc biệt. Bởi có cảm hứng cộng với bản tính người Việt Nam thông minh tế nhị, nên Thiền Việt Nam trở thành thi vị. Quý vị đọc lại sử của Thiền sư Việt Nam, sẽ thấy đa số các Ngài thích nói kệ, nói thi chớ không đánh, không hét.

Như tôi đã nói, chủ trương của chúng tôi là khôi phục Thiền tông đời Trần. Nếu nói theo sử Phật giáo của dân tộc ta thì từ thế kỷ thứ 6 thứ 7 có Thiền Tỳ Ni Đa Lưu Chi. Ngài Tỳ Ni Đa Lưu Chi là người Ấn truyền Thiền sang Việt Nam. Tới thế kỷ thứ 8 thứ 9 có Thiền của ngài Vô Ngôn Thông là người Hoa truyền sang nước ta. Đến thế kỷ 12, 13 tức đời nhà Trần, thì vua Trần Nhân Tông đi tu lập ra hệ phái Trúc Lâm Yên Tử, Ngài là Sơ Tổ.

Ngài đã thu nhặt tinh hoa những hệ Thiền trước kết tụ lại thành Thiền Việt Nam, lấy tên là Thiền Trúc Lâm Yên Tử. Như vậy Sơ Tổ dòng thiền này là người Việt Nam, một ông vua Việt Nam. Nói tới khôi phục Thiền tông đời Trần, tức là khôi phục Thiền tông Việt Nam. Dòng Thiền này rất gần gũi với chúng ta, vì nó mang tính dân tộc, mang bản sắc Việt Nam. Đó là ý nghĩa tôi nói khôi phục Thiền tông Việt Nam.

Thêm một vấn đề nữa trên phương diện thời cơ. Như khi tôi lập Thiền viện Thường Chiếu cho Tăng Ni tu, đồng thời tôi cũng lập Tuệ Tĩnh Đường hốt thuốc miễn phí cho dân. Bởi vì theo hoàn cảnh riêng biệt của mỗi địa phương mà chúng ta có những phương tiện giáo hóa khác nhau. Ở Thường Chiếu chung quanh là dân nghèo, chúng tôi lập Tuệ Tĩnh Đường để vừa tu, vừa giúp đỡ đồng bào. Đó là việc thích hợp với hoàn cảnh nơi đây, nên được mọi người hưởng ứng. Vì thế việc giáo hóa sẽ có nhiều thuận lợi.

Đến khi lập Thiền viện Trúc Lâm, tôi không mở Tuệ Tĩnh Đường nữa mà tạo cảnh quan đẹp cho khách du lịch đến viếng. Như vậy tùy điều kiện ở mỗi nơi mà tôi làm việc này hay việc nọ. Ở chỗ dân nghèo cần thuốc men thì có Tuệ Tĩnh đường. Còn Đà Lạt là thành phố du lịch, cần thu hút được khách du lịch thì dân ở đó mới có phương tiện sống. Như vậy chúng ta tạo duyên để người ta tới đông, dân ở đó mới có phương tiện làm ăn sinh sống. Đây cũng là cách để giúp cho dân nơi này. Thành ra tùy thời, tùy căn cơ mà chúng ta có những việc làm khác nhau. Cốt làm sao cho thích ứng với hoàn cảnh của xã hội hiện tại, vừa lợi đạo vừa ích đời.

Đó là tôi nói đại khái để chúng ta thấy người truyền đạo, giáo hóa phải biết thời biết cơ, ứng dụng cho thích hợp. Như Phật dạy tùy hoàn cảnh, vua chúa Ngài nói khác, dân dã Ngài nói khác, làm sao cho người nghe thu nhặt được kết quả tốt. Như vậy việc giáo hóa mới đem lợi ích lại cho mọi người.

Như thời hiện tại này và tương lai mai sau, chúng ta thấy truyền bá Tịnh độ là thích hợp hay truyền bá Thiền thích hợp? Đó là vấn đề tôi muốn đặt ra cho tất cả huynh đệ nhìn kỹ, xét kỹ. Nói thế tôi phải đi xa hơn một chút.

Thuở còn nhỏ, tôi biết nước Việt Nam chỉ có một trường Đại học Y Khoa đặt ở Hà Nội. Miền Trung không có trường học công lập. Miền Nam, ở Sài Gòn chỉ có trường Pétrus Ký *(nam)* với trường Gia Long *(nữ)*. Các Tỉnh thì Mỹ Tho có trường trung học Nguyễn Đình Chiểu, Cần Thơ có trường trung học Ba Sắc. Ở tại Huyện, ngày xưa gọi là Quận chỉ có trường Tiểu học từ lớp Năm tới lớp Nhứt *(bây giờ gọi là lớp Một tới lớp Năm)*. Ở Xã chỉ có trường dạy từ lớp Một tới lớp Ba thôi, không có hơn nữa. Ngoài ra tất cả trường tư thục thì do nhà dòng lập ra, chứ nhà nước chỉ có mấy trường thôi. Như vậy dân trí của mình thời xưa như thế nào? Có thể nói hầu hết tới 90% người dốt hoặc chỉ được gọi là biết chữ, còn trí thức có 10% thôi. Mà 10% trí thức đó, đa số học ở các trường dòng, trường của mấy Ma sơ. Như vậy giới trí thức nghiêng về Công giáo, còn Phật giáo chẳng có bao nhiêu.

Trong hoàn cảnh như thế, nếu đạo Phật không dạy tu Tịnh độ thì đâu ai hiểu gì về Phật pháp mà tu. Cho nên chỉ có pháp môn Tịnh độ là thích hợp trong thời đó. Nhưng tới thời này, quý vị nhìn lại xem nước ta có bao nhiêu trường Đại học? Từ Bắc chí Nam có rất nhiều trường Đại học. Ở mỗi Tỉnh cũng có Đại học hoặc hai ba Tỉnh có một trường Đại học. Tại Thủ đô Hà Nội có ba, bốn trường Đại học rồi Thành phố Hồ Chí Minh cũng nhiều trường Đại học. Các trường Trung học thì tại Xã cũng có nữa.

Như vậy con em chúng ta mai kia sẽ dốt như mình hồi trước hay là giỏi hơn, trí tuệ hơn? Nếu dốt hơn thì mình dạy pháp đơn giản nó mới hiểu, mới tu được. Còn nếu thông minh hơn, giỏi hơn mình thì dạy như vậy nó không chấp nhận đâu. Chúng ta phải thấy được điều đó.

Tôi nói hơi xa một chút, như năm tôi sang Pháp gần cuối mùa hè. Vừa tới Paris, thầy Nhất Hạnh điện thoại mời tôi xuống nói chuyện ở làng Hồng. Khi xuống, lớp học hè của thầy sắp mãn, số người ngoại quốc tham dự đến hai ngàn mấy trăm người. Hôm đó thầy mời tôi giảng. Tôi cười nói:

\- Tôi chỉ biết tiếng Việt Nam thôi, thầy bắt tôi giảng cho người ngoại quốc, làm sao tôi giảng được.

Thầy bảo rằng:

\- Thầy đừng ngại, cứ giảng. Nếu người nói tiếng Pháp họ sẽ ngồi một cụm, người nói tiếng Anh ngồi một cụm. Mỗi người có mang sẵn ống nghe, thầy giảng bằng tiếng Việt, dưới đó có người dịch ra ngay cho từng nhóm của họ. Tất cả đều được nghe rõ ràng, thầy không phải sợ.

Thành ra tôi nói tới đâu người ta nghe tới đó, chớ không có kiểu nói một câu, rồi ngồi chờ thông dịch viên dịch, xong mới nói câu nữa. Giảng kiểu đó thì buồn chết.

Hôm đó tôi giảng về đề tài Phật giáo Việt Nam. Tôi đề cao tinh thần của người phụ nữ Việt Nam, nhất là người phụ nữ Phật giáo. Vì Phật giáo Việt Nam từ Bắc chí Nam gần như  80% chùa đều thờ đức Quan Âm. Hoặc thờ trong chùa hoặc thờ lộ thiên. Như vậy Việt Nam rất tôn trọng phái nữ, vì đức tính tốt của người nữ là nhẫn nhục và từ bi. Tôi kể chùa ngoài Bắc, chùa nào cũng có thờ ông thiện, ông ác. Ông thiện thờ thì phải, sao lại thờ ông ác?

Nhân đó, tôi mới giải thích rằng ở Việt Nam sự tu hành luôn luôn có hai mặt; một mặt thì giúp đỡ khuyến khích tiến lên, còn một mặt thì phải răn đe dọa nạt cho người ta sợ. Với người hiền lành thì khuyến khích giúp đỡ cho họ tiến, với người hung dữ phải răn đe dọa nạt cho họ bỏ thói xấu. Cả hai mặt đều là Bồ-tát hết. Nói thế để người ngoại quốc thấy được cái hay của Phật giáo Việt Nam.

Giới trí thức Tây phương muốn tu Thiền, ham tu Thiền; còn giới trí thức Việt Nam có muốn tu Thiền không? Cũng muốn tu Thiền. Thiền lại là sở trường của Phật giáo Việt Nam từ thuở tổ tiên của chúng ta. Vậy mà chúng ta không khai thác sở trường của mình, để nó chìm vào quên lãng thì như vậy mình có lỗi không? Chính vì lẽ đó mà tôi chủ trương khôi phục Thiền tông Việt Nam. Khi tôi chủ trương làm việc này, ít ai vui vẻ chấp nhận. Nhưng vì tôi thấy cơ duyên của Phật giáo đến lúc phải như vậy, không thể khác hơn được. Bởi vì trong thời đại ngày nay, chỉ có tu Thiền là thích ứng với người trí thức trong cũng như ngoài nước.

Ngày xưa ông bà chúng ta ít học, cho nên dạy những gì cao xa không hiểu, buộc lòng phải dạy tu Tịnh độ. Các Ngài bảo cứ niệm Phật đi, niệm rồi Phật sẽ đón về bên đó sung sướng lắm, không như ở đây. Do dễ hiểu nên dễ chấp nhận, vì vậy người thời đó hoan hỷ tu theo. Nhưng bây giờ con cháu chúng ta khôn hơn chúng ta nhiều. Nó lý luận và hấp thụ nền văn minh của khoa học hiện đại, mà đã khoa học thì phải thực tế, phải được chứng minh cụ thể, chớ không nói suông được.

Thí dụ như khi ra Bắc, tôi thấy các chùa viết sớ bằng chữ Hán rồi đội trên đầu Phật tử, cúng vái. Tôi đặt câu hỏi, không biết đức Phật người Tàu hay người Ấn? Nếu Phật người Ấn mà viết chữ Hán, thì phải có thư ký dịch ra Phật mới hiểu được chớ. Còn nếu Phật có tha tâm thông, biết đủ hết tất cả các tiếng thì mình cứ lòng thành viết chữ Việt, Ngài đọc sẽ hiểu và sẽ thông cảm ngay, cực khổ gì phải viết chữ Hán cho khó khăn vậy. Chuyện đó thật làm sao đâu!

Như vậy mai chiều con em mình có chịu tin, chịu nghe, chịu làm những điều như vậy không? Đó là những việc mà người tu sĩ Phật giáo chúng ta, nhất là quý vị giảng sư phải am hiểu, phải phân định cho rõ ràng, chín chắn. Cái gì thích hợp với hoàn cảnh, thích hợp với thời đại, thích hợp với căn cơ của chúng sanh thì mình khuyến khích, mình phổ biến. Còn cái gì không thích hợp thì mình phải gác qua, phải xét nét và giải thích cho mọi người cùng hiểu kỹ càng. Nếu không như thế vô tình mình làm cho Phật giáo ngày càng bị quên lãng, càng bị chối bỏ. Đây là điều mà tôi thấy cần phải nói cho tất cả hiểu, thông cảm.

Gần đây ở Việt Nam chúng ta, người ngoại quốc tới xin tập tu ở Thiền viện khá nhiều. Như vậy họ sang Việt Nam và muốn nghiên cứu Thiền, muốn tu Thiền thì nơi nào dạy Thiền họ mới tới, còn không dạy Thiền họ sẽ không tới. Đó là điều dĩ nhiên thôi. Nên pháp môn được nhiều người đương thời trông cậy, mong chờ mà mình không biết, không dạy cho họ tu thì thật là uổng.

Hồi tôi còn dạy tại Vạn Hạnh, có dự một buổi hội thảo. Đến giờ nghỉ giải lao, có một Giáo sư dạy trường Đại học Tổng Hợp đến gần than với tôi: *“Thưa thầy, tôi đang gặp một vấn đề nan giải”*. Tôi hỏi: *“Giáo sư gặp vấn đề gì nan giải quá vậy?”*. Ông mới kể: Ông là Giáo sư trường Đại học Tổng Hợp, là trưởng khoa Văn. Mới đây, bên Đức vừa gửi thư mời ông qua dự hội thảo về Phật giáo đời Trần. Ông nói: *“Thưa thầy, tôi chưa nghiên cứu gì về vấn đề này cả”*.

Quý vị thấy rõ ràng người Tây phương mà còn chú ý tới Phật giáo đời Trần của chúng ta như vậy. Trong khi đó người Việt Nam lại hết sức lơ là, không để ý tới gì cả. Nhất là giới tu sĩ, không cần biết Phật giáo nước nhà như thế nào, có những điểm gì đặc biệt. Như vậy chúng ta có đáng trách không? Nếu ra ngoại quốc, bị người ta hỏi Phật giáo đời Trần như thế nào, những gì ưu, những gì khuyết mình đều không biết, có phải xấu hổ không?

Cho nên là giảng sư thì quý vị phải nghiên cứu, phải hiểu cho rõ tương lai Phật giáo của chúng ta như thế nào, nên truyền giáo làm sao cho thích ứng, cho phù hợp thời đại. Có vậy mới mong nối nắm được mạng mạch của Phật pháp. Bằng không, chính là chúng ta tự làm cho đạo pháp đi vào suy vi vậy.

Mong rằng quý vị giảng sư cố gắng tìm hiểu nghiên cứu cho kỹ, để giảng dạy cho mọi người biết bệnh, biết thuốc trị. Tôi xin nhắc lại lần nữa, chúng ta là người quảng cáo đạo Phật hay là ông thầy thuốc nhỏ, đệ tử đệ tôn của Vua thầy thuốc? Quý vị chịu làm gì? Chịu làm quảng cáo hay chịu làm thầy thuốc con? Nếu là thầy thuốc con thì phải học thuốc, học cách trị bệnh y như cha mình, để làm sao cho mọi người được lành bệnh. Đó mới đúng là con Vua thầy thuốc.

Tôi hy vọng buổi nói chuyện hôm nay sẽ đem lại nhiều lợi ích cho tất cả quý vị, trên bước đường tu đạo cũng như hành đạo của mình.
